package com.rstech.wordwatch.dao.mapper;

import com.rstech.wordwatch.dao.RSUserLimit;
import com.rstech.wordwatch.dao.RSUserLimitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RSUserLimitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user_lmt
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int countByExample(RSUserLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user_lmt
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int deleteByExample(RSUserLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user_lmt
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int deleteByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user_lmt
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int insert(RSUserLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user_lmt
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int insertSelective(RSUserLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user_lmt
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    List<RSUserLimit> selectByExample(RSUserLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user_lmt
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    RSUserLimit selectByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user_lmt
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int updateByExampleSelective(@Param("record") RSUserLimit record, @Param("example") RSUserLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user_lmt
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int updateByExample(@Param("record") RSUserLimit record, @Param("example") RSUserLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user_lmt
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int updateByPrimaryKeySelective(RSUserLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user_lmt
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int updateByPrimaryKey(RSUserLimit record);
}