package com.rstech.wordwatch.dao.mapper;

import com.rstech.wordwatch.dao.WordReport;
import com.rstech.wordwatch.dao.WordReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int countByExample(WordReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int deleteByExample(WordReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int deleteByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int insert(WordReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int insertSelective(WordReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    List<WordReport> selectByExample(WordReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    WordReport selectByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int updateByExampleSelective(@Param("record") WordReport record, @Param("example") WordReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int updateByExample(@Param("record") WordReport record, @Param("example") WordReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int updateByPrimaryKeySelective(WordReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    int updateByPrimaryKey(WordReport record);
}