package com.rstech.wordwatch.dao.mapper;

import com.rstech.wordwatch.dao.RSSearchLimitDomainTable;
import com.rstech.wordwatch.dao.RSSearchLimitDomainTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RSSearchLimitDomainTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_srch_lmt_dmn_tbl
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int countByExample(RSSearchLimitDomainTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_srch_lmt_dmn_tbl
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int deleteByExample(RSSearchLimitDomainTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_srch_lmt_dmn_tbl
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_srch_lmt_dmn_tbl
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int insert(RSSearchLimitDomainTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_srch_lmt_dmn_tbl
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int insertSelective(RSSearchLimitDomainTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_srch_lmt_dmn_tbl
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    List<RSSearchLimitDomainTable> selectByExample(RSSearchLimitDomainTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_srch_lmt_dmn_tbl
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    RSSearchLimitDomainTable selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_srch_lmt_dmn_tbl
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByExampleSelective(@Param("record") RSSearchLimitDomainTable record, @Param("example") RSSearchLimitDomainTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_srch_lmt_dmn_tbl
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByExample(@Param("record") RSSearchLimitDomainTable record, @Param("example") RSSearchLimitDomainTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_srch_lmt_dmn_tbl
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByPrimaryKeySelective(RSSearchLimitDomainTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_srch_lmt_dmn_tbl
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByPrimaryKey(RSSearchLimitDomainTable record);
}