package com.rstech.wordwatch.dao.mapper;

import com.rstech.wordwatch.dao.ScrLoginsAndLogouts;
import com.rstech.wordwatch.dao.ScrLoginsAndLogoutsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScrLoginsAndLogoutsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logins_and_logouts
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int countByExample(ScrLoginsAndLogoutsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logins_and_logouts
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int deleteByExample(ScrLoginsAndLogoutsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logins_and_logouts
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int deleteByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logins_and_logouts
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int insert(ScrLoginsAndLogouts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logins_and_logouts
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int insertSelective(ScrLoginsAndLogouts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logins_and_logouts
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    List<ScrLoginsAndLogouts> selectByExample(ScrLoginsAndLogoutsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logins_and_logouts
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    ScrLoginsAndLogouts selectByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logins_and_logouts
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByExampleSelective(@Param("record") ScrLoginsAndLogouts record, @Param("example") ScrLoginsAndLogoutsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logins_and_logouts
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByExample(@Param("record") ScrLoginsAndLogouts record, @Param("example") ScrLoginsAndLogoutsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logins_and_logouts
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByPrimaryKeySelective(ScrLoginsAndLogouts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logins_and_logouts
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByPrimaryKey(ScrLoginsAndLogouts record);
}