package com.rstech.wordwatch.dao.mapper;

import com.rstech.wordwatch.dao.WordReportEntry;
import com.rstech.wordwatch.dao.WordReportEntryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordReportEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int countByExample(WordReportEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int deleteByExample(WordReportEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int deleteByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int insert(WordReportEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int insertSelective(WordReportEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    List<WordReportEntry> selectByExample(WordReportEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    WordReportEntry selectByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByExampleSelective(@Param("record") WordReportEntry record, @Param("example") WordReportEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByExample(@Param("record") WordReportEntry record, @Param("example") WordReportEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByPrimaryKeySelective(WordReportEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByPrimaryKey(WordReportEntry record);
}