package com.rstech.wordwatch.dao.mapper;

import com.rstech.wordwatch.dao.WordReportEntryAux;
import com.rstech.wordwatch.dao.WordReportEntryAuxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordReportEntryAuxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry_aux
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int countByExample(WordReportEntryAuxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry_aux
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int deleteByExample(WordReportEntryAuxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry_aux
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int deleteByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry_aux
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int insert(WordReportEntryAux record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry_aux
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int insertSelective(WordReportEntryAux record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry_aux
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    List<WordReportEntryAux> selectByExample(WordReportEntryAuxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry_aux
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    WordReportEntryAux selectByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry_aux
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByExampleSelective(@Param("record") WordReportEntryAux record, @Param("example") WordReportEntryAuxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry_aux
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByExample(@Param("record") WordReportEntryAux record, @Param("example") WordReportEntryAuxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry_aux
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByPrimaryKeySelective(WordReportEntryAux record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report_entry_aux
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    int updateByPrimaryKey(WordReportEntryAux record);
}