package com.rstech.wordwatch.dao.client.test;

import com.rstech.wordwatch.dao.RSUser;
import com.rstech.wordwatch.dao.RSUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RSUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int countByExample(RSUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int deleteByExample(RSUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int deleteByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int insert(RSUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int insertSelective(RSUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    List<RSUser> selectByExample(RSUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    RSUser selectByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int updateByExampleSelective(@Param("record") RSUser record, @Param("example") RSUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int updateByExample(@Param("record") RSUser record, @Param("example") RSUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int updateByPrimaryKeySelective(RSUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int updateByPrimaryKey(RSUser record);
}