package com.rstech.wordwatch.dao.client.test;

import com.rstech.wordwatch.dao.WDUserReport;
import com.rstech.wordwatch.dao.WDUserReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WDUserReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_report_view
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int countByExample(WDUserReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_report_view
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int deleteByExample(WDUserReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_report_view
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int deleteByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_report_view
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int insert(WDUserReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_report_view
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int insertSelective(WDUserReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_report_view
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    List<WDUserReport> selectByExample(WDUserReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_report_view
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    WDUserReport selectByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_report_view
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int updateByExampleSelective(@Param("record") WDUserReport record, @Param("example") WDUserReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_report_view
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int updateByExample(@Param("record") WDUserReport record, @Param("example") WDUserReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_report_view
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int updateByPrimaryKeySelective(WDUserReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_user_report_view
     *
     * @mbggenerated Tue Oct 20 19:59:29 EDT 2015
     */
    int updateByPrimaryKey(WDUserReport record);
}