package com.rstech.wordwatch.dao;

import java.util.ArrayList;
import java.util.List;

public class RSClientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public RSClientExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(Long value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(Long value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(Long value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(Long value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<Long> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<Long> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andNAMEIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNAMEIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNAMEEqualTo(String value) {
            addCriterion("NAME =", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotEqualTo(String value) {
            addCriterion("NAME <>", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEGreaterThan(String value) {
            addCriterion("NAME >", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMELessThan(String value) {
            addCriterion("NAME <", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMELessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMELike(String value) {
            addCriterion("NAME like", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotLike(String value) {
            addCriterion("NAME not like", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEIn(List<String> values) {
            addCriterion("NAME in", values, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotIn(List<String> values) {
            addCriterion("NAME not in", values, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "NAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMEIsNull() {
            addCriterion("DISPLAY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMEIsNotNull() {
            addCriterion("DISPLAY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMEEqualTo(String value) {
            addCriterion("DISPLAY_NAME =", value, "DISPLAY_NAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMENotEqualTo(String value) {
            addCriterion("DISPLAY_NAME <>", value, "DISPLAY_NAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMEGreaterThan(String value) {
            addCriterion("DISPLAY_NAME >", value, "DISPLAY_NAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("DISPLAY_NAME >=", value, "DISPLAY_NAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMELessThan(String value) {
            addCriterion("DISPLAY_NAME <", value, "DISPLAY_NAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMELessThanOrEqualTo(String value) {
            addCriterion("DISPLAY_NAME <=", value, "DISPLAY_NAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMELike(String value) {
            addCriterion("DISPLAY_NAME like", value, "DISPLAY_NAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMENotLike(String value) {
            addCriterion("DISPLAY_NAME not like", value, "DISPLAY_NAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMEIn(List<String> values) {
            addCriterion("DISPLAY_NAME in", values, "DISPLAY_NAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMENotIn(List<String> values) {
            addCriterion("DISPLAY_NAME not in", values, "DISPLAY_NAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMEBetween(String value1, String value2) {
            addCriterion("DISPLAY_NAME between", value1, value2, "DISPLAY_NAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_NAMENotBetween(String value1, String value2) {
            addCriterion("DISPLAY_NAME not between", value1, value2, "DISPLAY_NAME");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDIsNull() {
            addCriterion("IS_DELETED is null");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDIsNotNull() {
            addCriterion("IS_DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDEqualTo(String value) {
            addCriterion("IS_DELETED =", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotEqualTo(String value) {
            addCriterion("IS_DELETED <>", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDGreaterThan(String value) {
            addCriterion("IS_DELETED >", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DELETED >=", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDLessThan(String value) {
            addCriterion("IS_DELETED <", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDLessThanOrEqualTo(String value) {
            addCriterion("IS_DELETED <=", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDLike(String value) {
            addCriterion("IS_DELETED like", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotLike(String value) {
            addCriterion("IS_DELETED not like", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDIn(List<String> values) {
            addCriterion("IS_DELETED in", values, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotIn(List<String> values) {
            addCriterion("IS_DELETED not in", values, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDBetween(String value1, String value2) {
            addCriterion("IS_DELETED between", value1, value2, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotBetween(String value1, String value2) {
            addCriterion("IS_DELETED not between", value1, value2, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andADDRESS1IsNull() {
            addCriterion("ADDRESS1 is null");
            return (Criteria) this;
        }

        public Criteria andADDRESS1IsNotNull() {
            addCriterion("ADDRESS1 is not null");
            return (Criteria) this;
        }

        public Criteria andADDRESS1EqualTo(String value) {
            addCriterion("ADDRESS1 =", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1NotEqualTo(String value) {
            addCriterion("ADDRESS1 <>", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1GreaterThan(String value) {
            addCriterion("ADDRESS1 >", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1GreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS1 >=", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1LessThan(String value) {
            addCriterion("ADDRESS1 <", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1LessThanOrEqualTo(String value) {
            addCriterion("ADDRESS1 <=", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1Like(String value) {
            addCriterion("ADDRESS1 like", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1NotLike(String value) {
            addCriterion("ADDRESS1 not like", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1In(List<String> values) {
            addCriterion("ADDRESS1 in", values, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1NotIn(List<String> values) {
            addCriterion("ADDRESS1 not in", values, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1Between(String value1, String value2) {
            addCriterion("ADDRESS1 between", value1, value2, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1NotBetween(String value1, String value2) {
            addCriterion("ADDRESS1 not between", value1, value2, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS2IsNull() {
            addCriterion("ADDRESS2 is null");
            return (Criteria) this;
        }

        public Criteria andADDRESS2IsNotNull() {
            addCriterion("ADDRESS2 is not null");
            return (Criteria) this;
        }

        public Criteria andADDRESS2EqualTo(String value) {
            addCriterion("ADDRESS2 =", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2NotEqualTo(String value) {
            addCriterion("ADDRESS2 <>", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2GreaterThan(String value) {
            addCriterion("ADDRESS2 >", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2GreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS2 >=", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2LessThan(String value) {
            addCriterion("ADDRESS2 <", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2LessThanOrEqualTo(String value) {
            addCriterion("ADDRESS2 <=", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2Like(String value) {
            addCriterion("ADDRESS2 like", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2NotLike(String value) {
            addCriterion("ADDRESS2 not like", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2In(List<String> values) {
            addCriterion("ADDRESS2 in", values, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2NotIn(List<String> values) {
            addCriterion("ADDRESS2 not in", values, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2Between(String value1, String value2) {
            addCriterion("ADDRESS2 between", value1, value2, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2NotBetween(String value1, String value2) {
            addCriterion("ADDRESS2 not between", value1, value2, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCITYIsNull() {
            addCriterion("CITY is null");
            return (Criteria) this;
        }

        public Criteria andCITYIsNotNull() {
            addCriterion("CITY is not null");
            return (Criteria) this;
        }

        public Criteria andCITYEqualTo(String value) {
            addCriterion("CITY =", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYNotEqualTo(String value) {
            addCriterion("CITY <>", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYGreaterThan(String value) {
            addCriterion("CITY >", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYLessThan(String value) {
            addCriterion("CITY <", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYLike(String value) {
            addCriterion("CITY like", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYNotLike(String value) {
            addCriterion("CITY not like", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYIn(List<String> values) {
            addCriterion("CITY in", values, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYNotIn(List<String> values) {
            addCriterion("CITY not in", values, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "CITY");
            return (Criteria) this;
        }

        public Criteria andSTATEIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andSTATEIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andSTATEEqualTo(String value) {
            addCriterion("STATE =", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATENotEqualTo(String value) {
            addCriterion("STATE <>", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATEGreaterThan(String value) {
            addCriterion("STATE >", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATEGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATELessThan(String value) {
            addCriterion("STATE <", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATELessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATELike(String value) {
            addCriterion("STATE like", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATENotLike(String value) {
            addCriterion("STATE not like", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATEIn(List<String> values) {
            addCriterion("STATE in", values, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATENotIn(List<String> values) {
            addCriterion("STATE not in", values, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATEBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATENotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "STATE");
            return (Criteria) this;
        }

        public Criteria andZIPIsNull() {
            addCriterion("ZIP is null");
            return (Criteria) this;
        }

        public Criteria andZIPIsNotNull() {
            addCriterion("ZIP is not null");
            return (Criteria) this;
        }

        public Criteria andZIPEqualTo(String value) {
            addCriterion("ZIP =", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPNotEqualTo(String value) {
            addCriterion("ZIP <>", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPGreaterThan(String value) {
            addCriterion("ZIP >", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPGreaterThanOrEqualTo(String value) {
            addCriterion("ZIP >=", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPLessThan(String value) {
            addCriterion("ZIP <", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPLessThanOrEqualTo(String value) {
            addCriterion("ZIP <=", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPLike(String value) {
            addCriterion("ZIP like", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPNotLike(String value) {
            addCriterion("ZIP not like", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPIn(List<String> values) {
            addCriterion("ZIP in", values, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPNotIn(List<String> values) {
            addCriterion("ZIP not in", values, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPBetween(String value1, String value2) {
            addCriterion("ZIP between", value1, value2, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPNotBetween(String value1, String value2) {
            addCriterion("ZIP not between", value1, value2, "ZIP");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYIsNull() {
            addCriterion("COUNTRY is null");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYIsNotNull() {
            addCriterion("COUNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYEqualTo(String value) {
            addCriterion("COUNTRY =", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYNotEqualTo(String value) {
            addCriterion("COUNTRY <>", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYGreaterThan(String value) {
            addCriterion("COUNTRY >", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYGreaterThanOrEqualTo(String value) {
            addCriterion("COUNTRY >=", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYLessThan(String value) {
            addCriterion("COUNTRY <", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYLessThanOrEqualTo(String value) {
            addCriterion("COUNTRY <=", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYLike(String value) {
            addCriterion("COUNTRY like", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYNotLike(String value) {
            addCriterion("COUNTRY not like", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYIn(List<String> values) {
            addCriterion("COUNTRY in", values, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYNotIn(List<String> values) {
            addCriterion("COUNTRY not in", values, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYBetween(String value1, String value2) {
            addCriterion("COUNTRY between", value1, value2, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYNotBetween(String value1, String value2) {
            addCriterion("COUNTRY not between", value1, value2, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andVERSIONIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVERSIONIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVERSIONEqualTo(Integer value) {
            addCriterion("VERSION =", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONLessThan(Integer value) {
            addCriterion("VERSION <", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONIn(List<Integer> values) {
            addCriterion("VERSION in", values, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "VERSION");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESIsNull() {
            addCriterion("SHOW_KEYFIND_NOTES is null");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESIsNotNull() {
            addCriterion("SHOW_KEYFIND_NOTES is not null");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESEqualTo(String value) {
            addCriterion("SHOW_KEYFIND_NOTES =", value, "SHOW_KEYFIND_NOTES");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESNotEqualTo(String value) {
            addCriterion("SHOW_KEYFIND_NOTES <>", value, "SHOW_KEYFIND_NOTES");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESGreaterThan(String value) {
            addCriterion("SHOW_KEYFIND_NOTES >", value, "SHOW_KEYFIND_NOTES");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESGreaterThanOrEqualTo(String value) {
            addCriterion("SHOW_KEYFIND_NOTES >=", value, "SHOW_KEYFIND_NOTES");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESLessThan(String value) {
            addCriterion("SHOW_KEYFIND_NOTES <", value, "SHOW_KEYFIND_NOTES");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESLessThanOrEqualTo(String value) {
            addCriterion("SHOW_KEYFIND_NOTES <=", value, "SHOW_KEYFIND_NOTES");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESLike(String value) {
            addCriterion("SHOW_KEYFIND_NOTES like", value, "SHOW_KEYFIND_NOTES");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESNotLike(String value) {
            addCriterion("SHOW_KEYFIND_NOTES not like", value, "SHOW_KEYFIND_NOTES");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESIn(List<String> values) {
            addCriterion("SHOW_KEYFIND_NOTES in", values, "SHOW_KEYFIND_NOTES");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESNotIn(List<String> values) {
            addCriterion("SHOW_KEYFIND_NOTES not in", values, "SHOW_KEYFIND_NOTES");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESBetween(String value1, String value2) {
            addCriterion("SHOW_KEYFIND_NOTES between", value1, value2, "SHOW_KEYFIND_NOTES");
            return (Criteria) this;
        }

        public Criteria andSHOW_KEYFIND_NOTESNotBetween(String value1, String value2) {
            addCriterion("SHOW_KEYFIND_NOTES not between", value1, value2, "SHOW_KEYFIND_NOTES");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNIsNull() {
            addCriterion("IS_LOGOUT_BTN_SHOWN is null");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNIsNotNull() {
            addCriterion("IS_LOGOUT_BTN_SHOWN is not null");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNEqualTo(String value) {
            addCriterion("IS_LOGOUT_BTN_SHOWN =", value, "IS_LOGOUT_BTN_SHOWN");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNNotEqualTo(String value) {
            addCriterion("IS_LOGOUT_BTN_SHOWN <>", value, "IS_LOGOUT_BTN_SHOWN");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNGreaterThan(String value) {
            addCriterion("IS_LOGOUT_BTN_SHOWN >", value, "IS_LOGOUT_BTN_SHOWN");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNGreaterThanOrEqualTo(String value) {
            addCriterion("IS_LOGOUT_BTN_SHOWN >=", value, "IS_LOGOUT_BTN_SHOWN");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNLessThan(String value) {
            addCriterion("IS_LOGOUT_BTN_SHOWN <", value, "IS_LOGOUT_BTN_SHOWN");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNLessThanOrEqualTo(String value) {
            addCriterion("IS_LOGOUT_BTN_SHOWN <=", value, "IS_LOGOUT_BTN_SHOWN");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNLike(String value) {
            addCriterion("IS_LOGOUT_BTN_SHOWN like", value, "IS_LOGOUT_BTN_SHOWN");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNNotLike(String value) {
            addCriterion("IS_LOGOUT_BTN_SHOWN not like", value, "IS_LOGOUT_BTN_SHOWN");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNIn(List<String> values) {
            addCriterion("IS_LOGOUT_BTN_SHOWN in", values, "IS_LOGOUT_BTN_SHOWN");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNNotIn(List<String> values) {
            addCriterion("IS_LOGOUT_BTN_SHOWN not in", values, "IS_LOGOUT_BTN_SHOWN");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNBetween(String value1, String value2) {
            addCriterion("IS_LOGOUT_BTN_SHOWN between", value1, value2, "IS_LOGOUT_BTN_SHOWN");
            return (Criteria) this;
        }

        public Criteria andIS_LOGOUT_BTN_SHOWNNotBetween(String value1, String value2) {
            addCriterion("IS_LOGOUT_BTN_SHOWN not between", value1, value2, "IS_LOGOUT_BTN_SHOWN");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rs_client
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 04 20:46:26 EDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rs_client
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}