package com.rstech.wordwatch.dao;

public class RSClient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.ID
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.NAME
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.DISPLAY_NAME
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String DISPLAY_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.IS_DELETED
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String IS_DELETED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.ADDRESS1
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String ADDRESS1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.ADDRESS2
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String ADDRESS2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.CITY
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String CITY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.STATE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String STATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.ZIP
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String ZIP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.COUNTRY
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String COUNTRY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.VERSION
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private Integer VERSION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.SHOW_KEYFIND_NOTES
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String SHOW_KEYFIND_NOTES;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_client.IS_LOGOUT_BTN_SHOWN
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String IS_LOGOUT_BTN_SHOWN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.ID
     *
     * @return the value of rs_client.ID
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.ID
     *
     * @param ID the value for rs_client.ID
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.NAME
     *
     * @return the value of rs_client.NAME
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.NAME
     *
     * @param NAME the value for rs_client.NAME
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.DISPLAY_NAME
     *
     * @return the value of rs_client.DISPLAY_NAME
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getDISPLAY_NAME() {
        return DISPLAY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.DISPLAY_NAME
     *
     * @param DISPLAY_NAME the value for rs_client.DISPLAY_NAME
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setDISPLAY_NAME(String DISPLAY_NAME) {
        this.DISPLAY_NAME = DISPLAY_NAME == null ? null : DISPLAY_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.IS_DELETED
     *
     * @return the value of rs_client.IS_DELETED
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getIS_DELETED() {
        return IS_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.IS_DELETED
     *
     * @param IS_DELETED the value for rs_client.IS_DELETED
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setIS_DELETED(String IS_DELETED) {
        this.IS_DELETED = IS_DELETED == null ? null : IS_DELETED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.ADDRESS1
     *
     * @return the value of rs_client.ADDRESS1
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getADDRESS1() {
        return ADDRESS1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.ADDRESS1
     *
     * @param ADDRESS1 the value for rs_client.ADDRESS1
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setADDRESS1(String ADDRESS1) {
        this.ADDRESS1 = ADDRESS1 == null ? null : ADDRESS1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.ADDRESS2
     *
     * @return the value of rs_client.ADDRESS2
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getADDRESS2() {
        return ADDRESS2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.ADDRESS2
     *
     * @param ADDRESS2 the value for rs_client.ADDRESS2
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setADDRESS2(String ADDRESS2) {
        this.ADDRESS2 = ADDRESS2 == null ? null : ADDRESS2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.CITY
     *
     * @return the value of rs_client.CITY
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getCITY() {
        return CITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.CITY
     *
     * @param CITY the value for rs_client.CITY
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setCITY(String CITY) {
        this.CITY = CITY == null ? null : CITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.STATE
     *
     * @return the value of rs_client.STATE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getSTATE() {
        return STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.STATE
     *
     * @param STATE the value for rs_client.STATE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setSTATE(String STATE) {
        this.STATE = STATE == null ? null : STATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.ZIP
     *
     * @return the value of rs_client.ZIP
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getZIP() {
        return ZIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.ZIP
     *
     * @param ZIP the value for rs_client.ZIP
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setZIP(String ZIP) {
        this.ZIP = ZIP == null ? null : ZIP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.COUNTRY
     *
     * @return the value of rs_client.COUNTRY
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getCOUNTRY() {
        return COUNTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.COUNTRY
     *
     * @param COUNTRY the value for rs_client.COUNTRY
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setCOUNTRY(String COUNTRY) {
        this.COUNTRY = COUNTRY == null ? null : COUNTRY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.VERSION
     *
     * @return the value of rs_client.VERSION
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Integer getVERSION() {
        return VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.VERSION
     *
     * @param VERSION the value for rs_client.VERSION
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setVERSION(Integer VERSION) {
        this.VERSION = VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.SHOW_KEYFIND_NOTES
     *
     * @return the value of rs_client.SHOW_KEYFIND_NOTES
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getSHOW_KEYFIND_NOTES() {
        return SHOW_KEYFIND_NOTES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.SHOW_KEYFIND_NOTES
     *
     * @param SHOW_KEYFIND_NOTES the value for rs_client.SHOW_KEYFIND_NOTES
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setSHOW_KEYFIND_NOTES(String SHOW_KEYFIND_NOTES) {
        this.SHOW_KEYFIND_NOTES = SHOW_KEYFIND_NOTES == null ? null : SHOW_KEYFIND_NOTES.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_client.IS_LOGOUT_BTN_SHOWN
     *
     * @return the value of rs_client.IS_LOGOUT_BTN_SHOWN
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getIS_LOGOUT_BTN_SHOWN() {
        return IS_LOGOUT_BTN_SHOWN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_client.IS_LOGOUT_BTN_SHOWN
     *
     * @param IS_LOGOUT_BTN_SHOWN the value for rs_client.IS_LOGOUT_BTN_SHOWN
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setIS_LOGOUT_BTN_SHOWN(String IS_LOGOUT_BTN_SHOWN) {
        this.IS_LOGOUT_BTN_SHOWN = IS_LOGOUT_BTN_SHOWN == null ? null : IS_LOGOUT_BTN_SHOWN.trim();
    }
}