package com.rstech.wordwatch.dao;

public class RSSearchLimitDomainTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_srch_lmt_dmn_tbl.ID
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_srch_lmt_dmn_tbl.DESC_TX
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String DESC_TX;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_srch_lmt_dmn_tbl.ID
     *
     * @return the value of rs_srch_lmt_dmn_tbl.ID
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_srch_lmt_dmn_tbl.ID
     *
     * @param ID the value for rs_srch_lmt_dmn_tbl.ID
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_srch_lmt_dmn_tbl.DESC_TX
     *
     * @return the value of rs_srch_lmt_dmn_tbl.DESC_TX
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getDESC_TX() {
        return DESC_TX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_srch_lmt_dmn_tbl.DESC_TX
     *
     * @param DESC_TX the value for rs_srch_lmt_dmn_tbl.DESC_TX
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setDESC_TX(String DESC_TX) {
        this.DESC_TX = DESC_TX == null ? null : DESC_TX.trim();
    }
}