package com.rstech.wordwatch.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RSUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public RSUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(Long value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(Long value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(Long value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(Long value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<Long> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<Long> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTIsNull() {
            addCriterion("RS_CLIENT is null");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTIsNotNull() {
            addCriterion("RS_CLIENT is not null");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTEqualTo(Long value) {
            addCriterion("RS_CLIENT =", value, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTNotEqualTo(Long value) {
            addCriterion("RS_CLIENT <>", value, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTGreaterThan(Long value) {
            addCriterion("RS_CLIENT >", value, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTGreaterThanOrEqualTo(Long value) {
            addCriterion("RS_CLIENT >=", value, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTLessThan(Long value) {
            addCriterion("RS_CLIENT <", value, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTLessThanOrEqualTo(Long value) {
            addCriterion("RS_CLIENT <=", value, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTIn(List<Long> values) {
            addCriterion("RS_CLIENT in", values, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTNotIn(List<Long> values) {
            addCriterion("RS_CLIENT not in", values, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTBetween(Long value1, Long value2) {
            addCriterion("RS_CLIENT between", value1, value2, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTNotBetween(Long value1, Long value2) {
            addCriterion("RS_CLIENT not between", value1, value2, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andLOGINIsNull() {
            addCriterion("LOGIN is null");
            return (Criteria) this;
        }

        public Criteria andLOGINIsNotNull() {
            addCriterion("LOGIN is not null");
            return (Criteria) this;
        }

        public Criteria andLOGINEqualTo(String value) {
            addCriterion("LOGIN =", value, "LOGIN");
            return (Criteria) this;
        }

        public Criteria andLOGINNotEqualTo(String value) {
            addCriterion("LOGIN <>", value, "LOGIN");
            return (Criteria) this;
        }

        public Criteria andLOGINGreaterThan(String value) {
            addCriterion("LOGIN >", value, "LOGIN");
            return (Criteria) this;
        }

        public Criteria andLOGINGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN >=", value, "LOGIN");
            return (Criteria) this;
        }

        public Criteria andLOGINLessThan(String value) {
            addCriterion("LOGIN <", value, "LOGIN");
            return (Criteria) this;
        }

        public Criteria andLOGINLessThanOrEqualTo(String value) {
            addCriterion("LOGIN <=", value, "LOGIN");
            return (Criteria) this;
        }

        public Criteria andLOGINLike(String value) {
            addCriterion("LOGIN like", value, "LOGIN");
            return (Criteria) this;
        }

        public Criteria andLOGINNotLike(String value) {
            addCriterion("LOGIN not like", value, "LOGIN");
            return (Criteria) this;
        }

        public Criteria andLOGINIn(List<String> values) {
            addCriterion("LOGIN in", values, "LOGIN");
            return (Criteria) this;
        }

        public Criteria andLOGINNotIn(List<String> values) {
            addCriterion("LOGIN not in", values, "LOGIN");
            return (Criteria) this;
        }

        public Criteria andLOGINBetween(String value1, String value2) {
            addCriterion("LOGIN between", value1, value2, "LOGIN");
            return (Criteria) this;
        }

        public Criteria andLOGINNotBetween(String value1, String value2) {
            addCriterion("LOGIN not between", value1, value2, "LOGIN");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMEIsNull() {
            addCriterion("FIRST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMEIsNotNull() {
            addCriterion("FIRST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMEEqualTo(String value) {
            addCriterion("FIRST_NAME =", value, "FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMENotEqualTo(String value) {
            addCriterion("FIRST_NAME <>", value, "FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMEGreaterThan(String value) {
            addCriterion("FIRST_NAME >", value, "FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("FIRST_NAME >=", value, "FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMELessThan(String value) {
            addCriterion("FIRST_NAME <", value, "FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMELessThanOrEqualTo(String value) {
            addCriterion("FIRST_NAME <=", value, "FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMELike(String value) {
            addCriterion("FIRST_NAME like", value, "FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMENotLike(String value) {
            addCriterion("FIRST_NAME not like", value, "FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMEIn(List<String> values) {
            addCriterion("FIRST_NAME in", values, "FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMENotIn(List<String> values) {
            addCriterion("FIRST_NAME not in", values, "FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMEBetween(String value1, String value2) {
            addCriterion("FIRST_NAME between", value1, value2, "FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andFIRST_NAMENotBetween(String value1, String value2) {
            addCriterion("FIRST_NAME not between", value1, value2, "FIRST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMEIsNull() {
            addCriterion("LAST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMEIsNotNull() {
            addCriterion("LAST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMEEqualTo(String value) {
            addCriterion("LAST_NAME =", value, "LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMENotEqualTo(String value) {
            addCriterion("LAST_NAME <>", value, "LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMEGreaterThan(String value) {
            addCriterion("LAST_NAME >", value, "LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_NAME >=", value, "LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMELessThan(String value) {
            addCriterion("LAST_NAME <", value, "LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMELessThanOrEqualTo(String value) {
            addCriterion("LAST_NAME <=", value, "LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMELike(String value) {
            addCriterion("LAST_NAME like", value, "LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMENotLike(String value) {
            addCriterion("LAST_NAME not like", value, "LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMEIn(List<String> values) {
            addCriterion("LAST_NAME in", values, "LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMENotIn(List<String> values) {
            addCriterion("LAST_NAME not in", values, "LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMEBetween(String value1, String value2) {
            addCriterion("LAST_NAME between", value1, value2, "LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andLAST_NAMENotBetween(String value1, String value2) {
            addCriterion("LAST_NAME not between", value1, value2, "LAST_NAME");
            return (Criteria) this;
        }

        public Criteria andPASSWORDIsNull() {
            addCriterion("PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andPASSWORDIsNotNull() {
            addCriterion("PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andPASSWORDEqualTo(String value) {
            addCriterion("PASSWORD =", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDLessThan(String value) {
            addCriterion("PASSWORD <", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDLike(String value) {
            addCriterion("PASSWORD like", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDNotLike(String value) {
            addCriterion("PASSWORD not like", value, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDIn(List<String> values) {
            addCriterion("PASSWORD in", values, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDNotIn(List<String> values) {
            addCriterion("PASSWORD not in", values, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andPASSWORDNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "PASSWORD");
            return (Criteria) this;
        }

        public Criteria andEMAILIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEMAILIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEMAILEqualTo(String value) {
            addCriterion("EMAIL =", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILGreaterThan(String value) {
            addCriterion("EMAIL >", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILLessThan(String value) {
            addCriterion("EMAIL <", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILLike(String value) {
            addCriterion("EMAIL like", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotLike(String value) {
            addCriterion("EMAIL not like", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILIn(List<String> values) {
            addCriterion("EMAIL in", values, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDIsNull() {
            addCriterion("IS_DELETED is null");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDIsNotNull() {
            addCriterion("IS_DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDEqualTo(String value) {
            addCriterion("IS_DELETED =", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotEqualTo(String value) {
            addCriterion("IS_DELETED <>", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDGreaterThan(String value) {
            addCriterion("IS_DELETED >", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DELETED >=", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDLessThan(String value) {
            addCriterion("IS_DELETED <", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDLessThanOrEqualTo(String value) {
            addCriterion("IS_DELETED <=", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDLike(String value) {
            addCriterion("IS_DELETED like", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotLike(String value) {
            addCriterion("IS_DELETED not like", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDIn(List<String> values) {
            addCriterion("IS_DELETED in", values, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotIn(List<String> values) {
            addCriterion("IS_DELETED not in", values, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDBetween(String value1, String value2) {
            addCriterion("IS_DELETED between", value1, value2, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotBetween(String value1, String value2) {
            addCriterion("IS_DELETED not between", value1, value2, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andPHONE1IsNull() {
            addCriterion("PHONE1 is null");
            return (Criteria) this;
        }

        public Criteria andPHONE1IsNotNull() {
            addCriterion("PHONE1 is not null");
            return (Criteria) this;
        }

        public Criteria andPHONE1EqualTo(String value) {
            addCriterion("PHONE1 =", value, "PHONE1");
            return (Criteria) this;
        }

        public Criteria andPHONE1NotEqualTo(String value) {
            addCriterion("PHONE1 <>", value, "PHONE1");
            return (Criteria) this;
        }

        public Criteria andPHONE1GreaterThan(String value) {
            addCriterion("PHONE1 >", value, "PHONE1");
            return (Criteria) this;
        }

        public Criteria andPHONE1GreaterThanOrEqualTo(String value) {
            addCriterion("PHONE1 >=", value, "PHONE1");
            return (Criteria) this;
        }

        public Criteria andPHONE1LessThan(String value) {
            addCriterion("PHONE1 <", value, "PHONE1");
            return (Criteria) this;
        }

        public Criteria andPHONE1LessThanOrEqualTo(String value) {
            addCriterion("PHONE1 <=", value, "PHONE1");
            return (Criteria) this;
        }

        public Criteria andPHONE1Like(String value) {
            addCriterion("PHONE1 like", value, "PHONE1");
            return (Criteria) this;
        }

        public Criteria andPHONE1NotLike(String value) {
            addCriterion("PHONE1 not like", value, "PHONE1");
            return (Criteria) this;
        }

        public Criteria andPHONE1In(List<String> values) {
            addCriterion("PHONE1 in", values, "PHONE1");
            return (Criteria) this;
        }

        public Criteria andPHONE1NotIn(List<String> values) {
            addCriterion("PHONE1 not in", values, "PHONE1");
            return (Criteria) this;
        }

        public Criteria andPHONE1Between(String value1, String value2) {
            addCriterion("PHONE1 between", value1, value2, "PHONE1");
            return (Criteria) this;
        }

        public Criteria andPHONE1NotBetween(String value1, String value2) {
            addCriterion("PHONE1 not between", value1, value2, "PHONE1");
            return (Criteria) this;
        }

        public Criteria andPHONE2IsNull() {
            addCriterion("PHONE2 is null");
            return (Criteria) this;
        }

        public Criteria andPHONE2IsNotNull() {
            addCriterion("PHONE2 is not null");
            return (Criteria) this;
        }

        public Criteria andPHONE2EqualTo(String value) {
            addCriterion("PHONE2 =", value, "PHONE2");
            return (Criteria) this;
        }

        public Criteria andPHONE2NotEqualTo(String value) {
            addCriterion("PHONE2 <>", value, "PHONE2");
            return (Criteria) this;
        }

        public Criteria andPHONE2GreaterThan(String value) {
            addCriterion("PHONE2 >", value, "PHONE2");
            return (Criteria) this;
        }

        public Criteria andPHONE2GreaterThanOrEqualTo(String value) {
            addCriterion("PHONE2 >=", value, "PHONE2");
            return (Criteria) this;
        }

        public Criteria andPHONE2LessThan(String value) {
            addCriterion("PHONE2 <", value, "PHONE2");
            return (Criteria) this;
        }

        public Criteria andPHONE2LessThanOrEqualTo(String value) {
            addCriterion("PHONE2 <=", value, "PHONE2");
            return (Criteria) this;
        }

        public Criteria andPHONE2Like(String value) {
            addCriterion("PHONE2 like", value, "PHONE2");
            return (Criteria) this;
        }

        public Criteria andPHONE2NotLike(String value) {
            addCriterion("PHONE2 not like", value, "PHONE2");
            return (Criteria) this;
        }

        public Criteria andPHONE2In(List<String> values) {
            addCriterion("PHONE2 in", values, "PHONE2");
            return (Criteria) this;
        }

        public Criteria andPHONE2NotIn(List<String> values) {
            addCriterion("PHONE2 not in", values, "PHONE2");
            return (Criteria) this;
        }

        public Criteria andPHONE2Between(String value1, String value2) {
            addCriterion("PHONE2 between", value1, value2, "PHONE2");
            return (Criteria) this;
        }

        public Criteria andPHONE2NotBetween(String value1, String value2) {
            addCriterion("PHONE2 not between", value1, value2, "PHONE2");
            return (Criteria) this;
        }

        public Criteria andADDRESS1IsNull() {
            addCriterion("ADDRESS1 is null");
            return (Criteria) this;
        }

        public Criteria andADDRESS1IsNotNull() {
            addCriterion("ADDRESS1 is not null");
            return (Criteria) this;
        }

        public Criteria andADDRESS1EqualTo(String value) {
            addCriterion("ADDRESS1 =", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1NotEqualTo(String value) {
            addCriterion("ADDRESS1 <>", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1GreaterThan(String value) {
            addCriterion("ADDRESS1 >", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1GreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS1 >=", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1LessThan(String value) {
            addCriterion("ADDRESS1 <", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1LessThanOrEqualTo(String value) {
            addCriterion("ADDRESS1 <=", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1Like(String value) {
            addCriterion("ADDRESS1 like", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1NotLike(String value) {
            addCriterion("ADDRESS1 not like", value, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1In(List<String> values) {
            addCriterion("ADDRESS1 in", values, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1NotIn(List<String> values) {
            addCriterion("ADDRESS1 not in", values, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1Between(String value1, String value2) {
            addCriterion("ADDRESS1 between", value1, value2, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS1NotBetween(String value1, String value2) {
            addCriterion("ADDRESS1 not between", value1, value2, "ADDRESS1");
            return (Criteria) this;
        }

        public Criteria andADDRESS2IsNull() {
            addCriterion("ADDRESS2 is null");
            return (Criteria) this;
        }

        public Criteria andADDRESS2IsNotNull() {
            addCriterion("ADDRESS2 is not null");
            return (Criteria) this;
        }

        public Criteria andADDRESS2EqualTo(String value) {
            addCriterion("ADDRESS2 =", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2NotEqualTo(String value) {
            addCriterion("ADDRESS2 <>", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2GreaterThan(String value) {
            addCriterion("ADDRESS2 >", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2GreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS2 >=", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2LessThan(String value) {
            addCriterion("ADDRESS2 <", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2LessThanOrEqualTo(String value) {
            addCriterion("ADDRESS2 <=", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2Like(String value) {
            addCriterion("ADDRESS2 like", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2NotLike(String value) {
            addCriterion("ADDRESS2 not like", value, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2In(List<String> values) {
            addCriterion("ADDRESS2 in", values, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2NotIn(List<String> values) {
            addCriterion("ADDRESS2 not in", values, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2Between(String value1, String value2) {
            addCriterion("ADDRESS2 between", value1, value2, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andADDRESS2NotBetween(String value1, String value2) {
            addCriterion("ADDRESS2 not between", value1, value2, "ADDRESS2");
            return (Criteria) this;
        }

        public Criteria andCITYIsNull() {
            addCriterion("CITY is null");
            return (Criteria) this;
        }

        public Criteria andCITYIsNotNull() {
            addCriterion("CITY is not null");
            return (Criteria) this;
        }

        public Criteria andCITYEqualTo(String value) {
            addCriterion("CITY =", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYNotEqualTo(String value) {
            addCriterion("CITY <>", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYGreaterThan(String value) {
            addCriterion("CITY >", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYLessThan(String value) {
            addCriterion("CITY <", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYLike(String value) {
            addCriterion("CITY like", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYNotLike(String value) {
            addCriterion("CITY not like", value, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYIn(List<String> values) {
            addCriterion("CITY in", values, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYNotIn(List<String> values) {
            addCriterion("CITY not in", values, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "CITY");
            return (Criteria) this;
        }

        public Criteria andCITYNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "CITY");
            return (Criteria) this;
        }

        public Criteria andSTATEIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andSTATEIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andSTATEEqualTo(String value) {
            addCriterion("STATE =", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATENotEqualTo(String value) {
            addCriterion("STATE <>", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATEGreaterThan(String value) {
            addCriterion("STATE >", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATEGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATELessThan(String value) {
            addCriterion("STATE <", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATELessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATELike(String value) {
            addCriterion("STATE like", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATENotLike(String value) {
            addCriterion("STATE not like", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATEIn(List<String> values) {
            addCriterion("STATE in", values, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATENotIn(List<String> values) {
            addCriterion("STATE not in", values, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATEBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATENotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "STATE");
            return (Criteria) this;
        }

        public Criteria andZIPIsNull() {
            addCriterion("ZIP is null");
            return (Criteria) this;
        }

        public Criteria andZIPIsNotNull() {
            addCriterion("ZIP is not null");
            return (Criteria) this;
        }

        public Criteria andZIPEqualTo(String value) {
            addCriterion("ZIP =", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPNotEqualTo(String value) {
            addCriterion("ZIP <>", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPGreaterThan(String value) {
            addCriterion("ZIP >", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPGreaterThanOrEqualTo(String value) {
            addCriterion("ZIP >=", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPLessThan(String value) {
            addCriterion("ZIP <", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPLessThanOrEqualTo(String value) {
            addCriterion("ZIP <=", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPLike(String value) {
            addCriterion("ZIP like", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPNotLike(String value) {
            addCriterion("ZIP not like", value, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPIn(List<String> values) {
            addCriterion("ZIP in", values, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPNotIn(List<String> values) {
            addCriterion("ZIP not in", values, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPBetween(String value1, String value2) {
            addCriterion("ZIP between", value1, value2, "ZIP");
            return (Criteria) this;
        }

        public Criteria andZIPNotBetween(String value1, String value2) {
            addCriterion("ZIP not between", value1, value2, "ZIP");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYIsNull() {
            addCriterion("COUNTRY is null");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYIsNotNull() {
            addCriterion("COUNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYEqualTo(String value) {
            addCriterion("COUNTRY =", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYNotEqualTo(String value) {
            addCriterion("COUNTRY <>", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYGreaterThan(String value) {
            addCriterion("COUNTRY >", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYGreaterThanOrEqualTo(String value) {
            addCriterion("COUNTRY >=", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYLessThan(String value) {
            addCriterion("COUNTRY <", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYLessThanOrEqualTo(String value) {
            addCriterion("COUNTRY <=", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYLike(String value) {
            addCriterion("COUNTRY like", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYNotLike(String value) {
            addCriterion("COUNTRY not like", value, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYIn(List<String> values) {
            addCriterion("COUNTRY in", values, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYNotIn(List<String> values) {
            addCriterion("COUNTRY not in", values, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYBetween(String value1, String value2) {
            addCriterion("COUNTRY between", value1, value2, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andCOUNTRYNotBetween(String value1, String value2) {
            addCriterion("COUNTRY not between", value1, value2, "COUNTRY");
            return (Criteria) this;
        }

        public Criteria andVERSIONIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVERSIONIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVERSIONEqualTo(Integer value) {
            addCriterion("VERSION =", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONLessThan(Integer value) {
            addCriterion("VERSION <", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONIn(List<Integer> values) {
            addCriterion("VERSION in", values, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "VERSION");
            return (Criteria) this;
        }

        public Criteria andFAXIsNull() {
            addCriterion("FAX is null");
            return (Criteria) this;
        }

        public Criteria andFAXIsNotNull() {
            addCriterion("FAX is not null");
            return (Criteria) this;
        }

        public Criteria andFAXEqualTo(String value) {
            addCriterion("FAX =", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXNotEqualTo(String value) {
            addCriterion("FAX <>", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXGreaterThan(String value) {
            addCriterion("FAX >", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXGreaterThanOrEqualTo(String value) {
            addCriterion("FAX >=", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXLessThan(String value) {
            addCriterion("FAX <", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXLessThanOrEqualTo(String value) {
            addCriterion("FAX <=", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXLike(String value) {
            addCriterion("FAX like", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXNotLike(String value) {
            addCriterion("FAX not like", value, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXIn(List<String> values) {
            addCriterion("FAX in", values, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXNotIn(List<String> values) {
            addCriterion("FAX not in", values, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXBetween(String value1, String value2) {
            addCriterion("FAX between", value1, value2, "FAX");
            return (Criteria) this;
        }

        public Criteria andFAXNotBetween(String value1, String value2) {
            addCriterion("FAX not between", value1, value2, "FAX");
            return (Criteria) this;
        }

        public Criteria andTITLEIsNull() {
            addCriterion("TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTITLEIsNotNull() {
            addCriterion("TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTITLEEqualTo(String value) {
            addCriterion("TITLE =", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLENotEqualTo(String value) {
            addCriterion("TITLE <>", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLEGreaterThan(String value) {
            addCriterion("TITLE >", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLEGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLELessThan(String value) {
            addCriterion("TITLE <", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLELessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLELike(String value) {
            addCriterion("TITLE like", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLENotLike(String value) {
            addCriterion("TITLE not like", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLEIn(List<String> values) {
            addCriterion("TITLE in", values, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLENotIn(List<String> values) {
            addCriterion("TITLE not in", values, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLEBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLENotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "TITLE");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDIsNull() {
            addCriterion("IS_LOCKED is null");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDIsNotNull() {
            addCriterion("IS_LOCKED is not null");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDEqualTo(String value) {
            addCriterion("IS_LOCKED =", value, "IS_LOCKED");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDNotEqualTo(String value) {
            addCriterion("IS_LOCKED <>", value, "IS_LOCKED");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDGreaterThan(String value) {
            addCriterion("IS_LOCKED >", value, "IS_LOCKED");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDGreaterThanOrEqualTo(String value) {
            addCriterion("IS_LOCKED >=", value, "IS_LOCKED");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDLessThan(String value) {
            addCriterion("IS_LOCKED <", value, "IS_LOCKED");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDLessThanOrEqualTo(String value) {
            addCriterion("IS_LOCKED <=", value, "IS_LOCKED");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDLike(String value) {
            addCriterion("IS_LOCKED like", value, "IS_LOCKED");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDNotLike(String value) {
            addCriterion("IS_LOCKED not like", value, "IS_LOCKED");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDIn(List<String> values) {
            addCriterion("IS_LOCKED in", values, "IS_LOCKED");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDNotIn(List<String> values) {
            addCriterion("IS_LOCKED not in", values, "IS_LOCKED");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDBetween(String value1, String value2) {
            addCriterion("IS_LOCKED between", value1, value2, "IS_LOCKED");
            return (Criteria) this;
        }

        public Criteria andIS_LOCKEDNotBetween(String value1, String value2) {
            addCriterion("IS_LOCKED not between", value1, value2, "IS_LOCKED");
            return (Criteria) this;
        }

        public Criteria andFAILED_LOGIN_ATTEMPTSIsNull() {
            addCriterion("FAILED_LOGIN_ATTEMPTS is null");
            return (Criteria) this;
        }

        public Criteria andFAILED_LOGIN_ATTEMPTSIsNotNull() {
            addCriterion("FAILED_LOGIN_ATTEMPTS is not null");
            return (Criteria) this;
        }

        public Criteria andFAILED_LOGIN_ATTEMPTSEqualTo(Short value) {
            addCriterion("FAILED_LOGIN_ATTEMPTS =", value, "FAILED_LOGIN_ATTEMPTS");
            return (Criteria) this;
        }

        public Criteria andFAILED_LOGIN_ATTEMPTSNotEqualTo(Short value) {
            addCriterion("FAILED_LOGIN_ATTEMPTS <>", value, "FAILED_LOGIN_ATTEMPTS");
            return (Criteria) this;
        }

        public Criteria andFAILED_LOGIN_ATTEMPTSGreaterThan(Short value) {
            addCriterion("FAILED_LOGIN_ATTEMPTS >", value, "FAILED_LOGIN_ATTEMPTS");
            return (Criteria) this;
        }

        public Criteria andFAILED_LOGIN_ATTEMPTSGreaterThanOrEqualTo(Short value) {
            addCriterion("FAILED_LOGIN_ATTEMPTS >=", value, "FAILED_LOGIN_ATTEMPTS");
            return (Criteria) this;
        }

        public Criteria andFAILED_LOGIN_ATTEMPTSLessThan(Short value) {
            addCriterion("FAILED_LOGIN_ATTEMPTS <", value, "FAILED_LOGIN_ATTEMPTS");
            return (Criteria) this;
        }

        public Criteria andFAILED_LOGIN_ATTEMPTSLessThanOrEqualTo(Short value) {
            addCriterion("FAILED_LOGIN_ATTEMPTS <=", value, "FAILED_LOGIN_ATTEMPTS");
            return (Criteria) this;
        }

        public Criteria andFAILED_LOGIN_ATTEMPTSIn(List<Short> values) {
            addCriterion("FAILED_LOGIN_ATTEMPTS in", values, "FAILED_LOGIN_ATTEMPTS");
            return (Criteria) this;
        }

        public Criteria andFAILED_LOGIN_ATTEMPTSNotIn(List<Short> values) {
            addCriterion("FAILED_LOGIN_ATTEMPTS not in", values, "FAILED_LOGIN_ATTEMPTS");
            return (Criteria) this;
        }

        public Criteria andFAILED_LOGIN_ATTEMPTSBetween(Short value1, Short value2) {
            addCriterion("FAILED_LOGIN_ATTEMPTS between", value1, value2, "FAILED_LOGIN_ATTEMPTS");
            return (Criteria) this;
        }

        public Criteria andFAILED_LOGIN_ATTEMPTSNotBetween(Short value1, Short value2) {
            addCriterion("FAILED_LOGIN_ATTEMPTS not between", value1, value2, "FAILED_LOGIN_ATTEMPTS");
            return (Criteria) this;
        }

        public Criteria andUSER_TP_NOIsNull() {
            addCriterion("USER_TP_NO is null");
            return (Criteria) this;
        }

        public Criteria andUSER_TP_NOIsNotNull() {
            addCriterion("USER_TP_NO is not null");
            return (Criteria) this;
        }

        public Criteria andUSER_TP_NOEqualTo(Integer value) {
            addCriterion("USER_TP_NO =", value, "USER_TP_NO");
            return (Criteria) this;
        }

        public Criteria andUSER_TP_NONotEqualTo(Integer value) {
            addCriterion("USER_TP_NO <>", value, "USER_TP_NO");
            return (Criteria) this;
        }

        public Criteria andUSER_TP_NOGreaterThan(Integer value) {
            addCriterion("USER_TP_NO >", value, "USER_TP_NO");
            return (Criteria) this;
        }

        public Criteria andUSER_TP_NOGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_TP_NO >=", value, "USER_TP_NO");
            return (Criteria) this;
        }

        public Criteria andUSER_TP_NOLessThan(Integer value) {
            addCriterion("USER_TP_NO <", value, "USER_TP_NO");
            return (Criteria) this;
        }

        public Criteria andUSER_TP_NOLessThanOrEqualTo(Integer value) {
            addCriterion("USER_TP_NO <=", value, "USER_TP_NO");
            return (Criteria) this;
        }

        public Criteria andUSER_TP_NOIn(List<Integer> values) {
            addCriterion("USER_TP_NO in", values, "USER_TP_NO");
            return (Criteria) this;
        }

        public Criteria andUSER_TP_NONotIn(List<Integer> values) {
            addCriterion("USER_TP_NO not in", values, "USER_TP_NO");
            return (Criteria) this;
        }

        public Criteria andUSER_TP_NOBetween(Integer value1, Integer value2) {
            addCriterion("USER_TP_NO between", value1, value2, "USER_TP_NO");
            return (Criteria) this;
        }

        public Criteria andUSER_TP_NONotBetween(Integer value1, Integer value2) {
            addCriterion("USER_TP_NO not between", value1, value2, "USER_TP_NO");
            return (Criteria) this;
        }

        public Criteria andPRNT_IDIsNull() {
            addCriterion("PRNT_ID is null");
            return (Criteria) this;
        }

        public Criteria andPRNT_IDIsNotNull() {
            addCriterion("PRNT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPRNT_IDEqualTo(Long value) {
            addCriterion("PRNT_ID =", value, "PRNT_ID");
            return (Criteria) this;
        }

        public Criteria andPRNT_IDNotEqualTo(Long value) {
            addCriterion("PRNT_ID <>", value, "PRNT_ID");
            return (Criteria) this;
        }

        public Criteria andPRNT_IDGreaterThan(Long value) {
            addCriterion("PRNT_ID >", value, "PRNT_ID");
            return (Criteria) this;
        }

        public Criteria andPRNT_IDGreaterThanOrEqualTo(Long value) {
            addCriterion("PRNT_ID >=", value, "PRNT_ID");
            return (Criteria) this;
        }

        public Criteria andPRNT_IDLessThan(Long value) {
            addCriterion("PRNT_ID <", value, "PRNT_ID");
            return (Criteria) this;
        }

        public Criteria andPRNT_IDLessThanOrEqualTo(Long value) {
            addCriterion("PRNT_ID <=", value, "PRNT_ID");
            return (Criteria) this;
        }

        public Criteria andPRNT_IDIn(List<Long> values) {
            addCriterion("PRNT_ID in", values, "PRNT_ID");
            return (Criteria) this;
        }

        public Criteria andPRNT_IDNotIn(List<Long> values) {
            addCriterion("PRNT_ID not in", values, "PRNT_ID");
            return (Criteria) this;
        }

        public Criteria andPRNT_IDBetween(Long value1, Long value2) {
            addCriterion("PRNT_ID between", value1, value2, "PRNT_ID");
            return (Criteria) this;
        }

        public Criteria andPRNT_IDNotBetween(Long value1, Long value2) {
            addCriterion("PRNT_ID not between", value1, value2, "PRNT_ID");
            return (Criteria) this;
        }

        public Criteria andSORT_ORDER_NOIsNull() {
            addCriterion("SORT_ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andSORT_ORDER_NOIsNotNull() {
            addCriterion("SORT_ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSORT_ORDER_NOEqualTo(Integer value) {
            addCriterion("SORT_ORDER_NO =", value, "SORT_ORDER_NO");
            return (Criteria) this;
        }

        public Criteria andSORT_ORDER_NONotEqualTo(Integer value) {
            addCriterion("SORT_ORDER_NO <>", value, "SORT_ORDER_NO");
            return (Criteria) this;
        }

        public Criteria andSORT_ORDER_NOGreaterThan(Integer value) {
            addCriterion("SORT_ORDER_NO >", value, "SORT_ORDER_NO");
            return (Criteria) this;
        }

        public Criteria andSORT_ORDER_NOGreaterThanOrEqualTo(Integer value) {
            addCriterion("SORT_ORDER_NO >=", value, "SORT_ORDER_NO");
            return (Criteria) this;
        }

        public Criteria andSORT_ORDER_NOLessThan(Integer value) {
            addCriterion("SORT_ORDER_NO <", value, "SORT_ORDER_NO");
            return (Criteria) this;
        }

        public Criteria andSORT_ORDER_NOLessThanOrEqualTo(Integer value) {
            addCriterion("SORT_ORDER_NO <=", value, "SORT_ORDER_NO");
            return (Criteria) this;
        }

        public Criteria andSORT_ORDER_NOIn(List<Integer> values) {
            addCriterion("SORT_ORDER_NO in", values, "SORT_ORDER_NO");
            return (Criteria) this;
        }

        public Criteria andSORT_ORDER_NONotIn(List<Integer> values) {
            addCriterion("SORT_ORDER_NO not in", values, "SORT_ORDER_NO");
            return (Criteria) this;
        }

        public Criteria andSORT_ORDER_NOBetween(Integer value1, Integer value2) {
            addCriterion("SORT_ORDER_NO between", value1, value2, "SORT_ORDER_NO");
            return (Criteria) this;
        }

        public Criteria andSORT_ORDER_NONotBetween(Integer value1, Integer value2) {
            addCriterion("SORT_ORDER_NO not between", value1, value2, "SORT_ORDER_NO");
            return (Criteria) this;
        }

        public Criteria andLAST_MODIFIED_TSIsNull() {
            addCriterion("LAST_MODIFIED_TS is null");
            return (Criteria) this;
        }

        public Criteria andLAST_MODIFIED_TSIsNotNull() {
            addCriterion("LAST_MODIFIED_TS is not null");
            return (Criteria) this;
        }

        public Criteria andLAST_MODIFIED_TSEqualTo(Date value) {
            addCriterion("LAST_MODIFIED_TS =", value, "LAST_MODIFIED_TS");
            return (Criteria) this;
        }

        public Criteria andLAST_MODIFIED_TSNotEqualTo(Date value) {
            addCriterion("LAST_MODIFIED_TS <>", value, "LAST_MODIFIED_TS");
            return (Criteria) this;
        }

        public Criteria andLAST_MODIFIED_TSGreaterThan(Date value) {
            addCriterion("LAST_MODIFIED_TS >", value, "LAST_MODIFIED_TS");
            return (Criteria) this;
        }

        public Criteria andLAST_MODIFIED_TSGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_MODIFIED_TS >=", value, "LAST_MODIFIED_TS");
            return (Criteria) this;
        }

        public Criteria andLAST_MODIFIED_TSLessThan(Date value) {
            addCriterion("LAST_MODIFIED_TS <", value, "LAST_MODIFIED_TS");
            return (Criteria) this;
        }

        public Criteria andLAST_MODIFIED_TSLessThanOrEqualTo(Date value) {
            addCriterion("LAST_MODIFIED_TS <=", value, "LAST_MODIFIED_TS");
            return (Criteria) this;
        }

        public Criteria andLAST_MODIFIED_TSIn(List<Date> values) {
            addCriterion("LAST_MODIFIED_TS in", values, "LAST_MODIFIED_TS");
            return (Criteria) this;
        }

        public Criteria andLAST_MODIFIED_TSNotIn(List<Date> values) {
            addCriterion("LAST_MODIFIED_TS not in", values, "LAST_MODIFIED_TS");
            return (Criteria) this;
        }

        public Criteria andLAST_MODIFIED_TSBetween(Date value1, Date value2) {
            addCriterion("LAST_MODIFIED_TS between", value1, value2, "LAST_MODIFIED_TS");
            return (Criteria) this;
        }

        public Criteria andLAST_MODIFIED_TSNotBetween(Date value1, Date value2) {
            addCriterion("LAST_MODIFIED_TS not between", value1, value2, "LAST_MODIFIED_TS");
            return (Criteria) this;
        }

        public Criteria andMODIFIED_BY_IDIsNull() {
            addCriterion("MODIFIED_BY_ID is null");
            return (Criteria) this;
        }

        public Criteria andMODIFIED_BY_IDIsNotNull() {
            addCriterion("MODIFIED_BY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMODIFIED_BY_IDEqualTo(Long value) {
            addCriterion("MODIFIED_BY_ID =", value, "MODIFIED_BY_ID");
            return (Criteria) this;
        }

        public Criteria andMODIFIED_BY_IDNotEqualTo(Long value) {
            addCriterion("MODIFIED_BY_ID <>", value, "MODIFIED_BY_ID");
            return (Criteria) this;
        }

        public Criteria andMODIFIED_BY_IDGreaterThan(Long value) {
            addCriterion("MODIFIED_BY_ID >", value, "MODIFIED_BY_ID");
            return (Criteria) this;
        }

        public Criteria andMODIFIED_BY_IDGreaterThanOrEqualTo(Long value) {
            addCriterion("MODIFIED_BY_ID >=", value, "MODIFIED_BY_ID");
            return (Criteria) this;
        }

        public Criteria andMODIFIED_BY_IDLessThan(Long value) {
            addCriterion("MODIFIED_BY_ID <", value, "MODIFIED_BY_ID");
            return (Criteria) this;
        }

        public Criteria andMODIFIED_BY_IDLessThanOrEqualTo(Long value) {
            addCriterion("MODIFIED_BY_ID <=", value, "MODIFIED_BY_ID");
            return (Criteria) this;
        }

        public Criteria andMODIFIED_BY_IDIn(List<Long> values) {
            addCriterion("MODIFIED_BY_ID in", values, "MODIFIED_BY_ID");
            return (Criteria) this;
        }

        public Criteria andMODIFIED_BY_IDNotIn(List<Long> values) {
            addCriterion("MODIFIED_BY_ID not in", values, "MODIFIED_BY_ID");
            return (Criteria) this;
        }

        public Criteria andMODIFIED_BY_IDBetween(Long value1, Long value2) {
            addCriterion("MODIFIED_BY_ID between", value1, value2, "MODIFIED_BY_ID");
            return (Criteria) this;
        }

        public Criteria andMODIFIED_BY_IDNotBetween(Long value1, Long value2) {
            addCriterion("MODIFIED_BY_ID not between", value1, value2, "MODIFIED_BY_ID");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rs_user
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 04 20:46:26 EDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rs_user
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}