package com.rstech.wordwatch.dao;

import java.util.Date;

public class RSUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.RS_CLIENT
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Long RS_CLIENT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.LOGIN
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String LOGIN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.FIRST_NAME
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String FIRST_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.LAST_NAME
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String LAST_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.PASSWORD
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String PASSWORD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.EMAIL
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String EMAIL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.IS_DELETED
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String IS_DELETED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.PHONE1
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String PHONE1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.PHONE2
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String PHONE2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.ADDRESS1
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String ADDRESS1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.ADDRESS2
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String ADDRESS2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.CITY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String CITY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.STATE
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String STATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.ZIP
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String ZIP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.COUNTRY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String COUNTRY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.VERSION
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Integer VERSION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.FAX
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String FAX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.TITLE
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String TITLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.IS_LOCKED
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String IS_LOCKED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.FAILED_LOGIN_ATTEMPTS
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Short FAILED_LOGIN_ATTEMPTS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.USER_TP_NO
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Integer USER_TP_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.PRNT_ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Long PRNT_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.SORT_ORDER_NO
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Integer SORT_ORDER_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.LAST_MODIFIED_TS
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Date LAST_MODIFIED_TS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rs_user.MODIFIED_BY_ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Long MODIFIED_BY_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.ID
     *
     * @return the value of rs_user.ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.ID
     *
     * @param ID the value for rs_user.ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.RS_CLIENT
     *
     * @return the value of rs_user.RS_CLIENT
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Long getRS_CLIENT() {
        return RS_CLIENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.RS_CLIENT
     *
     * @param RS_CLIENT the value for rs_user.RS_CLIENT
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setRS_CLIENT(Long RS_CLIENT) {
        this.RS_CLIENT = RS_CLIENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.LOGIN
     *
     * @return the value of rs_user.LOGIN
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getLOGIN() {
        return LOGIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.LOGIN
     *
     * @param LOGIN the value for rs_user.LOGIN
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setLOGIN(String LOGIN) {
        this.LOGIN = LOGIN == null ? null : LOGIN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.FIRST_NAME
     *
     * @return the value of rs_user.FIRST_NAME
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getFIRST_NAME() {
        return FIRST_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.FIRST_NAME
     *
     * @param FIRST_NAME the value for rs_user.FIRST_NAME
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setFIRST_NAME(String FIRST_NAME) {
        this.FIRST_NAME = FIRST_NAME == null ? null : FIRST_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.LAST_NAME
     *
     * @return the value of rs_user.LAST_NAME
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getLAST_NAME() {
        return LAST_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.LAST_NAME
     *
     * @param LAST_NAME the value for rs_user.LAST_NAME
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setLAST_NAME(String LAST_NAME) {
        this.LAST_NAME = LAST_NAME == null ? null : LAST_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.PASSWORD
     *
     * @return the value of rs_user.PASSWORD
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getPASSWORD() {
        return PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.PASSWORD
     *
     * @param PASSWORD the value for rs_user.PASSWORD
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD == null ? null : PASSWORD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.EMAIL
     *
     * @return the value of rs_user.EMAIL
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getEMAIL() {
        return EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.EMAIL
     *
     * @param EMAIL the value for rs_user.EMAIL
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setEMAIL(String EMAIL) {
        this.EMAIL = EMAIL == null ? null : EMAIL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.IS_DELETED
     *
     * @return the value of rs_user.IS_DELETED
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getIS_DELETED() {
        return IS_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.IS_DELETED
     *
     * @param IS_DELETED the value for rs_user.IS_DELETED
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setIS_DELETED(String IS_DELETED) {
        this.IS_DELETED = IS_DELETED == null ? null : IS_DELETED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.PHONE1
     *
     * @return the value of rs_user.PHONE1
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getPHONE1() {
        return PHONE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.PHONE1
     *
     * @param PHONE1 the value for rs_user.PHONE1
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setPHONE1(String PHONE1) {
        this.PHONE1 = PHONE1 == null ? null : PHONE1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.PHONE2
     *
     * @return the value of rs_user.PHONE2
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getPHONE2() {
        return PHONE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.PHONE2
     *
     * @param PHONE2 the value for rs_user.PHONE2
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setPHONE2(String PHONE2) {
        this.PHONE2 = PHONE2 == null ? null : PHONE2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.ADDRESS1
     *
     * @return the value of rs_user.ADDRESS1
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getADDRESS1() {
        return ADDRESS1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.ADDRESS1
     *
     * @param ADDRESS1 the value for rs_user.ADDRESS1
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setADDRESS1(String ADDRESS1) {
        this.ADDRESS1 = ADDRESS1 == null ? null : ADDRESS1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.ADDRESS2
     *
     * @return the value of rs_user.ADDRESS2
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getADDRESS2() {
        return ADDRESS2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.ADDRESS2
     *
     * @param ADDRESS2 the value for rs_user.ADDRESS2
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setADDRESS2(String ADDRESS2) {
        this.ADDRESS2 = ADDRESS2 == null ? null : ADDRESS2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.CITY
     *
     * @return the value of rs_user.CITY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getCITY() {
        return CITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.CITY
     *
     * @param CITY the value for rs_user.CITY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setCITY(String CITY) {
        this.CITY = CITY == null ? null : CITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.STATE
     *
     * @return the value of rs_user.STATE
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getSTATE() {
        return STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.STATE
     *
     * @param STATE the value for rs_user.STATE
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setSTATE(String STATE) {
        this.STATE = STATE == null ? null : STATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.ZIP
     *
     * @return the value of rs_user.ZIP
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getZIP() {
        return ZIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.ZIP
     *
     * @param ZIP the value for rs_user.ZIP
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setZIP(String ZIP) {
        this.ZIP = ZIP == null ? null : ZIP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.COUNTRY
     *
     * @return the value of rs_user.COUNTRY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getCOUNTRY() {
        return COUNTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.COUNTRY
     *
     * @param COUNTRY the value for rs_user.COUNTRY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setCOUNTRY(String COUNTRY) {
        this.COUNTRY = COUNTRY == null ? null : COUNTRY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.VERSION
     *
     * @return the value of rs_user.VERSION
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Integer getVERSION() {
        return VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.VERSION
     *
     * @param VERSION the value for rs_user.VERSION
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setVERSION(Integer VERSION) {
        this.VERSION = VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.FAX
     *
     * @return the value of rs_user.FAX
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getFAX() {
        return FAX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.FAX
     *
     * @param FAX the value for rs_user.FAX
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setFAX(String FAX) {
        this.FAX = FAX == null ? null : FAX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.TITLE
     *
     * @return the value of rs_user.TITLE
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getTITLE() {
        return TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.TITLE
     *
     * @param TITLE the value for rs_user.TITLE
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setTITLE(String TITLE) {
        this.TITLE = TITLE == null ? null : TITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.IS_LOCKED
     *
     * @return the value of rs_user.IS_LOCKED
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getIS_LOCKED() {
        return IS_LOCKED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.IS_LOCKED
     *
     * @param IS_LOCKED the value for rs_user.IS_LOCKED
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setIS_LOCKED(String IS_LOCKED) {
        this.IS_LOCKED = IS_LOCKED == null ? null : IS_LOCKED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.FAILED_LOGIN_ATTEMPTS
     *
     * @return the value of rs_user.FAILED_LOGIN_ATTEMPTS
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Short getFAILED_LOGIN_ATTEMPTS() {
        return FAILED_LOGIN_ATTEMPTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.FAILED_LOGIN_ATTEMPTS
     *
     * @param FAILED_LOGIN_ATTEMPTS the value for rs_user.FAILED_LOGIN_ATTEMPTS
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setFAILED_LOGIN_ATTEMPTS(Short FAILED_LOGIN_ATTEMPTS) {
        this.FAILED_LOGIN_ATTEMPTS = FAILED_LOGIN_ATTEMPTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.USER_TP_NO
     *
     * @return the value of rs_user.USER_TP_NO
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Integer getUSER_TP_NO() {
        return USER_TP_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.USER_TP_NO
     *
     * @param USER_TP_NO the value for rs_user.USER_TP_NO
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setUSER_TP_NO(Integer USER_TP_NO) {
        this.USER_TP_NO = USER_TP_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.PRNT_ID
     *
     * @return the value of rs_user.PRNT_ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Long getPRNT_ID() {
        return PRNT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.PRNT_ID
     *
     * @param PRNT_ID the value for rs_user.PRNT_ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setPRNT_ID(Long PRNT_ID) {
        this.PRNT_ID = PRNT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.SORT_ORDER_NO
     *
     * @return the value of rs_user.SORT_ORDER_NO
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Integer getSORT_ORDER_NO() {
        return SORT_ORDER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.SORT_ORDER_NO
     *
     * @param SORT_ORDER_NO the value for rs_user.SORT_ORDER_NO
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setSORT_ORDER_NO(Integer SORT_ORDER_NO) {
        this.SORT_ORDER_NO = SORT_ORDER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.LAST_MODIFIED_TS
     *
     * @return the value of rs_user.LAST_MODIFIED_TS
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Date getLAST_MODIFIED_TS() {
        return LAST_MODIFIED_TS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.LAST_MODIFIED_TS
     *
     * @param LAST_MODIFIED_TS the value for rs_user.LAST_MODIFIED_TS
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setLAST_MODIFIED_TS(Date LAST_MODIFIED_TS) {
        this.LAST_MODIFIED_TS = LAST_MODIFIED_TS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rs_user.MODIFIED_BY_ID
     *
     * @return the value of rs_user.MODIFIED_BY_ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Long getMODIFIED_BY_ID() {
        return MODIFIED_BY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rs_user.MODIFIED_BY_ID
     *
     * @param MODIFIED_BY_ID the value for rs_user.MODIFIED_BY_ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setMODIFIED_BY_ID(Long MODIFIED_BY_ID) {
        this.MODIFIED_BY_ID = MODIFIED_BY_ID;
    }
}