package com.rstech.wordwatch.dao;

public class WDUserReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_report_view.ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_report_view.RS_USER
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Long RS_USER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_report_view.WD_REPORT
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Long WD_REPORT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_report_view.IS_READ_ONLY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String IS_READ_ONLY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_user_report_view.VERSION
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Integer VERSION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_report_view.ID
     *
     * @return the value of wd_user_report_view.ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_report_view.ID
     *
     * @param ID the value for wd_user_report_view.ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_report_view.RS_USER
     *
     * @return the value of wd_user_report_view.RS_USER
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Long getRS_USER() {
        return RS_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_report_view.RS_USER
     *
     * @param RS_USER the value for wd_user_report_view.RS_USER
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setRS_USER(Long RS_USER) {
        this.RS_USER = RS_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_report_view.WD_REPORT
     *
     * @return the value of wd_user_report_view.WD_REPORT
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Long getWD_REPORT() {
        return WD_REPORT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_report_view.WD_REPORT
     *
     * @param WD_REPORT the value for wd_user_report_view.WD_REPORT
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setWD_REPORT(Long WD_REPORT) {
        this.WD_REPORT = WD_REPORT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_report_view.IS_READ_ONLY
     *
     * @return the value of wd_user_report_view.IS_READ_ONLY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getIS_READ_ONLY() {
        return IS_READ_ONLY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_report_view.IS_READ_ONLY
     *
     * @param IS_READ_ONLY the value for wd_user_report_view.IS_READ_ONLY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setIS_READ_ONLY(String IS_READ_ONLY) {
        this.IS_READ_ONLY = IS_READ_ONLY == null ? null : IS_READ_ONLY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_user_report_view.VERSION
     *
     * @return the value of wd_user_report_view.VERSION
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Integer getVERSION() {
        return VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_user_report_view.VERSION
     *
     * @param VERSION the value for wd_user_report_view.VERSION
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setVERSION(Integer VERSION) {
        this.VERSION = VERSION;
    }
}