package com.rstech.wordwatch.dao;

import java.util.ArrayList;
import java.util.List;

public class WordFieldListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public WordFieldListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(Long value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(Long value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(Long value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(Long value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<Long> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<Long> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andREC_TYPEIsNull() {
            addCriterion("REC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andREC_TYPEIsNotNull() {
            addCriterion("REC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andREC_TYPEEqualTo(String value) {
            addCriterion("REC_TYPE =", value, "REC_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_TYPENotEqualTo(String value) {
            addCriterion("REC_TYPE <>", value, "REC_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_TYPEGreaterThan(String value) {
            addCriterion("REC_TYPE >", value, "REC_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("REC_TYPE >=", value, "REC_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_TYPELessThan(String value) {
            addCriterion("REC_TYPE <", value, "REC_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_TYPELessThanOrEqualTo(String value) {
            addCriterion("REC_TYPE <=", value, "REC_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_TYPELike(String value) {
            addCriterion("REC_TYPE like", value, "REC_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_TYPENotLike(String value) {
            addCriterion("REC_TYPE not like", value, "REC_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_TYPEIn(List<String> values) {
            addCriterion("REC_TYPE in", values, "REC_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_TYPENotIn(List<String> values) {
            addCriterion("REC_TYPE not in", values, "REC_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_TYPEBetween(String value1, String value2) {
            addCriterion("REC_TYPE between", value1, value2, "REC_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_TYPENotBetween(String value1, String value2) {
            addCriterion("REC_TYPE not between", value1, value2, "REC_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPEIsNull() {
            addCriterion("REC_SUB_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPEIsNotNull() {
            addCriterion("REC_SUB_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPEEqualTo(String value) {
            addCriterion("REC_SUB_TYPE =", value, "REC_SUB_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPENotEqualTo(String value) {
            addCriterion("REC_SUB_TYPE <>", value, "REC_SUB_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPEGreaterThan(String value) {
            addCriterion("REC_SUB_TYPE >", value, "REC_SUB_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("REC_SUB_TYPE >=", value, "REC_SUB_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPELessThan(String value) {
            addCriterion("REC_SUB_TYPE <", value, "REC_SUB_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPELessThanOrEqualTo(String value) {
            addCriterion("REC_SUB_TYPE <=", value, "REC_SUB_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPELike(String value) {
            addCriterion("REC_SUB_TYPE like", value, "REC_SUB_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPENotLike(String value) {
            addCriterion("REC_SUB_TYPE not like", value, "REC_SUB_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPEIn(List<String> values) {
            addCriterion("REC_SUB_TYPE in", values, "REC_SUB_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPENotIn(List<String> values) {
            addCriterion("REC_SUB_TYPE not in", values, "REC_SUB_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPEBetween(String value1, String value2) {
            addCriterion("REC_SUB_TYPE between", value1, value2, "REC_SUB_TYPE");
            return (Criteria) this;
        }

        public Criteria andREC_SUB_TYPENotBetween(String value1, String value2) {
            addCriterion("REC_SUB_TYPE not between", value1, value2, "REC_SUB_TYPE");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMEIsNull() {
            addCriterion("FIELD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMEIsNotNull() {
            addCriterion("FIELD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMEEqualTo(String value) {
            addCriterion("FIELD_NAME =", value, "FIELD_NAME");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMENotEqualTo(String value) {
            addCriterion("FIELD_NAME <>", value, "FIELD_NAME");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMEGreaterThan(String value) {
            addCriterion("FIELD_NAME >", value, "FIELD_NAME");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("FIELD_NAME >=", value, "FIELD_NAME");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMELessThan(String value) {
            addCriterion("FIELD_NAME <", value, "FIELD_NAME");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMELessThanOrEqualTo(String value) {
            addCriterion("FIELD_NAME <=", value, "FIELD_NAME");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMELike(String value) {
            addCriterion("FIELD_NAME like", value, "FIELD_NAME");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMENotLike(String value) {
            addCriterion("FIELD_NAME not like", value, "FIELD_NAME");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMEIn(List<String> values) {
            addCriterion("FIELD_NAME in", values, "FIELD_NAME");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMENotIn(List<String> values) {
            addCriterion("FIELD_NAME not in", values, "FIELD_NAME");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMEBetween(String value1, String value2) {
            addCriterion("FIELD_NAME between", value1, value2, "FIELD_NAME");
            return (Criteria) this;
        }

        public Criteria andFIELD_NAMENotBetween(String value1, String value2) {
            addCriterion("FIELD_NAME not between", value1, value2, "FIELD_NAME");
            return (Criteria) this;
        }

        public Criteria andREQ_ORDERIsNull() {
            addCriterion("REQ_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andREQ_ORDERIsNotNull() {
            addCriterion("REQ_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andREQ_ORDEREqualTo(Short value) {
            addCriterion("REQ_ORDER =", value, "REQ_ORDER");
            return (Criteria) this;
        }

        public Criteria andREQ_ORDERNotEqualTo(Short value) {
            addCriterion("REQ_ORDER <>", value, "REQ_ORDER");
            return (Criteria) this;
        }

        public Criteria andREQ_ORDERGreaterThan(Short value) {
            addCriterion("REQ_ORDER >", value, "REQ_ORDER");
            return (Criteria) this;
        }

        public Criteria andREQ_ORDERGreaterThanOrEqualTo(Short value) {
            addCriterion("REQ_ORDER >=", value, "REQ_ORDER");
            return (Criteria) this;
        }

        public Criteria andREQ_ORDERLessThan(Short value) {
            addCriterion("REQ_ORDER <", value, "REQ_ORDER");
            return (Criteria) this;
        }

        public Criteria andREQ_ORDERLessThanOrEqualTo(Short value) {
            addCriterion("REQ_ORDER <=", value, "REQ_ORDER");
            return (Criteria) this;
        }

        public Criteria andREQ_ORDERIn(List<Short> values) {
            addCriterion("REQ_ORDER in", values, "REQ_ORDER");
            return (Criteria) this;
        }

        public Criteria andREQ_ORDERNotIn(List<Short> values) {
            addCriterion("REQ_ORDER not in", values, "REQ_ORDER");
            return (Criteria) this;
        }

        public Criteria andREQ_ORDERBetween(Short value1, Short value2) {
            addCriterion("REQ_ORDER between", value1, value2, "REQ_ORDER");
            return (Criteria) this;
        }

        public Criteria andREQ_ORDERNotBetween(Short value1, Short value2) {
            addCriterion("REQ_ORDER not between", value1, value2, "REQ_ORDER");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_ORDERIsNull() {
            addCriterion("DISPLAY_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_ORDERIsNotNull() {
            addCriterion("DISPLAY_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_ORDEREqualTo(Short value) {
            addCriterion("DISPLAY_ORDER =", value, "DISPLAY_ORDER");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_ORDERNotEqualTo(Short value) {
            addCriterion("DISPLAY_ORDER <>", value, "DISPLAY_ORDER");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_ORDERGreaterThan(Short value) {
            addCriterion("DISPLAY_ORDER >", value, "DISPLAY_ORDER");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_ORDERGreaterThanOrEqualTo(Short value) {
            addCriterion("DISPLAY_ORDER >=", value, "DISPLAY_ORDER");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_ORDERLessThan(Short value) {
            addCriterion("DISPLAY_ORDER <", value, "DISPLAY_ORDER");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_ORDERLessThanOrEqualTo(Short value) {
            addCriterion("DISPLAY_ORDER <=", value, "DISPLAY_ORDER");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_ORDERIn(List<Short> values) {
            addCriterion("DISPLAY_ORDER in", values, "DISPLAY_ORDER");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_ORDERNotIn(List<Short> values) {
            addCriterion("DISPLAY_ORDER not in", values, "DISPLAY_ORDER");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_ORDERBetween(Short value1, Short value2) {
            addCriterion("DISPLAY_ORDER between", value1, value2, "DISPLAY_ORDER");
            return (Criteria) this;
        }

        public Criteria andDISPLAY_ORDERNotBetween(Short value1, Short value2) {
            addCriterion("DISPLAY_ORDER not between", value1, value2, "DISPLAY_ORDER");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDIsNull() {
            addCriterion("IS_DELETED is null");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDIsNotNull() {
            addCriterion("IS_DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDEqualTo(String value) {
            addCriterion("IS_DELETED =", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotEqualTo(String value) {
            addCriterion("IS_DELETED <>", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDGreaterThan(String value) {
            addCriterion("IS_DELETED >", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DELETED >=", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDLessThan(String value) {
            addCriterion("IS_DELETED <", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDLessThanOrEqualTo(String value) {
            addCriterion("IS_DELETED <=", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDLike(String value) {
            addCriterion("IS_DELETED like", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotLike(String value) {
            addCriterion("IS_DELETED not like", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDIn(List<String> values) {
            addCriterion("IS_DELETED in", values, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotIn(List<String> values) {
            addCriterion("IS_DELETED not in", values, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDBetween(String value1, String value2) {
            addCriterion("IS_DELETED between", value1, value2, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotBetween(String value1, String value2) {
            addCriterion("IS_DELETED not between", value1, value2, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andVERSIONIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVERSIONIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVERSIONEqualTo(Integer value) {
            addCriterion("VERSION =", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONLessThan(Integer value) {
            addCriterion("VERSION <", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONIn(List<Integer> values) {
            addCriterion("VERSION in", values, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "VERSION");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_field_list
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 05 19:59:23 EST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_field_list
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}