package com.rstech.wordwatch.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class WordReportExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public WordReportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(Long value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(Long value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(Long value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(Long value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<Long> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<Long> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTIsNull() {
            addCriterion("RS_CLIENT is null");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTIsNotNull() {
            addCriterion("RS_CLIENT is not null");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTEqualTo(Long value) {
            addCriterion("RS_CLIENT =", value, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTNotEqualTo(Long value) {
            addCriterion("RS_CLIENT <>", value, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTGreaterThan(Long value) {
            addCriterion("RS_CLIENT >", value, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTGreaterThanOrEqualTo(Long value) {
            addCriterion("RS_CLIENT >=", value, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTLessThan(Long value) {
            addCriterion("RS_CLIENT <", value, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTLessThanOrEqualTo(Long value) {
            addCriterion("RS_CLIENT <=", value, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTIn(List<Long> values) {
            addCriterion("RS_CLIENT in", values, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTNotIn(List<Long> values) {
            addCriterion("RS_CLIENT not in", values, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTBetween(Long value1, Long value2) {
            addCriterion("RS_CLIENT between", value1, value2, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andRS_CLIENTNotBetween(Long value1, Long value2) {
            addCriterion("RS_CLIENT not between", value1, value2, "RS_CLIENT");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPEIsNull() {
            addCriterion("REPORT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPEIsNotNull() {
            addCriterion("REPORT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPEEqualTo(String value) {
            addCriterion("REPORT_TYPE =", value, "REPORT_TYPE");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPENotEqualTo(String value) {
            addCriterion("REPORT_TYPE <>", value, "REPORT_TYPE");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPEGreaterThan(String value) {
            addCriterion("REPORT_TYPE >", value, "REPORT_TYPE");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("REPORT_TYPE >=", value, "REPORT_TYPE");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPELessThan(String value) {
            addCriterion("REPORT_TYPE <", value, "REPORT_TYPE");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPELessThanOrEqualTo(String value) {
            addCriterion("REPORT_TYPE <=", value, "REPORT_TYPE");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPELike(String value) {
            addCriterion("REPORT_TYPE like", value, "REPORT_TYPE");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPENotLike(String value) {
            addCriterion("REPORT_TYPE not like", value, "REPORT_TYPE");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPEIn(List<String> values) {
            addCriterion("REPORT_TYPE in", values, "REPORT_TYPE");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPENotIn(List<String> values) {
            addCriterion("REPORT_TYPE not in", values, "REPORT_TYPE");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPEBetween(String value1, String value2) {
            addCriterion("REPORT_TYPE between", value1, value2, "REPORT_TYPE");
            return (Criteria) this;
        }

        public Criteria andREPORT_TYPENotBetween(String value1, String value2) {
            addCriterion("REPORT_TYPE not between", value1, value2, "REPORT_TYPE");
            return (Criteria) this;
        }

        public Criteria andTITLEIsNull() {
            addCriterion("TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTITLEIsNotNull() {
            addCriterion("TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTITLEEqualTo(String value) {
            addCriterion("TITLE =", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLENotEqualTo(String value) {
            addCriterion("TITLE <>", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLEGreaterThan(String value) {
            addCriterion("TITLE >", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLEGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLELessThan(String value) {
            addCriterion("TITLE <", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLELessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLELike(String value) {
            addCriterion("TITLE like", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLENotLike(String value) {
            addCriterion("TITLE not like", value, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLEIn(List<String> values) {
            addCriterion("TITLE in", values, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLENotIn(List<String> values) {
            addCriterion("TITLE not in", values, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLEBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "TITLE");
            return (Criteria) this;
        }

        public Criteria andTITLENotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "TITLE");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSTATUSEqualTo(String value) {
            addCriterion("STATUS =", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThan(String value) {
            addCriterion("STATUS >", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThan(String value) {
            addCriterion("STATUS <", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLike(String value) {
            addCriterion("STATUS like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotLike(String value) {
            addCriterion("STATUS not like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSIn(List<String> values) {
            addCriterion("STATUS in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andREPORTS_RUNIsNull() {
            addCriterion("REPORTS_RUN is null");
            return (Criteria) this;
        }

        public Criteria andREPORTS_RUNIsNotNull() {
            addCriterion("REPORTS_RUN is not null");
            return (Criteria) this;
        }

        public Criteria andREPORTS_RUNEqualTo(Short value) {
            addCriterion("REPORTS_RUN =", value, "REPORTS_RUN");
            return (Criteria) this;
        }

        public Criteria andREPORTS_RUNNotEqualTo(Short value) {
            addCriterion("REPORTS_RUN <>", value, "REPORTS_RUN");
            return (Criteria) this;
        }

        public Criteria andREPORTS_RUNGreaterThan(Short value) {
            addCriterion("REPORTS_RUN >", value, "REPORTS_RUN");
            return (Criteria) this;
        }

        public Criteria andREPORTS_RUNGreaterThanOrEqualTo(Short value) {
            addCriterion("REPORTS_RUN >=", value, "REPORTS_RUN");
            return (Criteria) this;
        }

        public Criteria andREPORTS_RUNLessThan(Short value) {
            addCriterion("REPORTS_RUN <", value, "REPORTS_RUN");
            return (Criteria) this;
        }

        public Criteria andREPORTS_RUNLessThanOrEqualTo(Short value) {
            addCriterion("REPORTS_RUN <=", value, "REPORTS_RUN");
            return (Criteria) this;
        }

        public Criteria andREPORTS_RUNIn(List<Short> values) {
            addCriterion("REPORTS_RUN in", values, "REPORTS_RUN");
            return (Criteria) this;
        }

        public Criteria andREPORTS_RUNNotIn(List<Short> values) {
            addCriterion("REPORTS_RUN not in", values, "REPORTS_RUN");
            return (Criteria) this;
        }

        public Criteria andREPORTS_RUNBetween(Short value1, Short value2) {
            addCriterion("REPORTS_RUN between", value1, value2, "REPORTS_RUN");
            return (Criteria) this;
        }

        public Criteria andREPORTS_RUNNotBetween(Short value1, Short value2) {
            addCriterion("REPORTS_RUN not between", value1, value2, "REPORTS_RUN");
            return (Criteria) this;
        }

        public Criteria andFIRST_RUN_DATEIsNull() {
            addCriterion("FIRST_RUN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andFIRST_RUN_DATEIsNotNull() {
            addCriterion("FIRST_RUN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andFIRST_RUN_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("FIRST_RUN_DATE =", value, "FIRST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andFIRST_RUN_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("FIRST_RUN_DATE <>", value, "FIRST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andFIRST_RUN_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("FIRST_RUN_DATE >", value, "FIRST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andFIRST_RUN_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FIRST_RUN_DATE >=", value, "FIRST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andFIRST_RUN_DATELessThan(Date value) {
            addCriterionForJDBCDate("FIRST_RUN_DATE <", value, "FIRST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andFIRST_RUN_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FIRST_RUN_DATE <=", value, "FIRST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andFIRST_RUN_DATEIn(List<Date> values) {
            addCriterionForJDBCDate("FIRST_RUN_DATE in", values, "FIRST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andFIRST_RUN_DATENotIn(List<Date> values) {
            addCriterionForJDBCDate("FIRST_RUN_DATE not in", values, "FIRST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andFIRST_RUN_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FIRST_RUN_DATE between", value1, value2, "FIRST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andFIRST_RUN_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FIRST_RUN_DATE not between", value1, value2, "FIRST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andLAST_RUN_DATEIsNull() {
            addCriterion("LAST_RUN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLAST_RUN_DATEIsNotNull() {
            addCriterion("LAST_RUN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLAST_RUN_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_RUN_DATE =", value, "LAST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andLAST_RUN_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_RUN_DATE <>", value, "LAST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andLAST_RUN_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("LAST_RUN_DATE >", value, "LAST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andLAST_RUN_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_RUN_DATE >=", value, "LAST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andLAST_RUN_DATELessThan(Date value) {
            addCriterionForJDBCDate("LAST_RUN_DATE <", value, "LAST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andLAST_RUN_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_RUN_DATE <=", value, "LAST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andLAST_RUN_DATEIn(List<Date> values) {
            addCriterionForJDBCDate("LAST_RUN_DATE in", values, "LAST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andLAST_RUN_DATENotIn(List<Date> values) {
            addCriterionForJDBCDate("LAST_RUN_DATE not in", values, "LAST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andLAST_RUN_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LAST_RUN_DATE between", value1, value2, "LAST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andLAST_RUN_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LAST_RUN_DATE not between", value1, value2, "LAST_RUN_DATE");
            return (Criteria) this;
        }

        public Criteria andEXPIRATION_DATEIsNull() {
            addCriterion("EXPIRATION_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEXPIRATION_DATEIsNotNull() {
            addCriterion("EXPIRATION_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEXPIRATION_DATEEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIRATION_DATE =", value, "EXPIRATION_DATE");
            return (Criteria) this;
        }

        public Criteria andEXPIRATION_DATENotEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIRATION_DATE <>", value, "EXPIRATION_DATE");
            return (Criteria) this;
        }

        public Criteria andEXPIRATION_DATEGreaterThan(Date value) {
            addCriterionForJDBCDate("EXPIRATION_DATE >", value, "EXPIRATION_DATE");
            return (Criteria) this;
        }

        public Criteria andEXPIRATION_DATEGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIRATION_DATE >=", value, "EXPIRATION_DATE");
            return (Criteria) this;
        }

        public Criteria andEXPIRATION_DATELessThan(Date value) {
            addCriterionForJDBCDate("EXPIRATION_DATE <", value, "EXPIRATION_DATE");
            return (Criteria) this;
        }

        public Criteria andEXPIRATION_DATELessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIRATION_DATE <=", value, "EXPIRATION_DATE");
            return (Criteria) this;
        }

        public Criteria andEXPIRATION_DATEIn(List<Date> values) {
            addCriterionForJDBCDate("EXPIRATION_DATE in", values, "EXPIRATION_DATE");
            return (Criteria) this;
        }

        public Criteria andEXPIRATION_DATENotIn(List<Date> values) {
            addCriterionForJDBCDate("EXPIRATION_DATE not in", values, "EXPIRATION_DATE");
            return (Criteria) this;
        }

        public Criteria andEXPIRATION_DATEBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPIRATION_DATE between", value1, value2, "EXPIRATION_DATE");
            return (Criteria) this;
        }

        public Criteria andEXPIRATION_DATENotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPIRATION_DATE not between", value1, value2, "EXPIRATION_DATE");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONLike(String value) {
            addCriterion("DESCRIPTION like", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDIsNull() {
            addCriterion("IS_DELETED is null");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDIsNotNull() {
            addCriterion("IS_DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDEqualTo(String value) {
            addCriterion("IS_DELETED =", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotEqualTo(String value) {
            addCriterion("IS_DELETED <>", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDGreaterThan(String value) {
            addCriterion("IS_DELETED >", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DELETED >=", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDLessThan(String value) {
            addCriterion("IS_DELETED <", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDLessThanOrEqualTo(String value) {
            addCriterion("IS_DELETED <=", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDLike(String value) {
            addCriterion("IS_DELETED like", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotLike(String value) {
            addCriterion("IS_DELETED not like", value, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDIn(List<String> values) {
            addCriterion("IS_DELETED in", values, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotIn(List<String> values) {
            addCriterion("IS_DELETED not in", values, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDBetween(String value1, String value2) {
            addCriterion("IS_DELETED between", value1, value2, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andIS_DELETEDNotBetween(String value1, String value2) {
            addCriterion("IS_DELETED not between", value1, value2, "IS_DELETED");
            return (Criteria) this;
        }

        public Criteria andVERSIONIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVERSIONIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVERSIONEqualTo(Integer value) {
            addCriterion("VERSION =", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONLessThan(Integer value) {
            addCriterion("VERSION <", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONIn(List<Integer> values) {
            addCriterion("VERSION in", values, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "VERSION");
            return (Criteria) this;
        }

        public Criteria andVERSIONNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "VERSION");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDIsNull() {
            addCriterion("IS_EXPIRED is null");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDIsNotNull() {
            addCriterion("IS_EXPIRED is not null");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDEqualTo(String value) {
            addCriterion("IS_EXPIRED =", value, "IS_EXPIRED");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDNotEqualTo(String value) {
            addCriterion("IS_EXPIRED <>", value, "IS_EXPIRED");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDGreaterThan(String value) {
            addCriterion("IS_EXPIRED >", value, "IS_EXPIRED");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDGreaterThanOrEqualTo(String value) {
            addCriterion("IS_EXPIRED >=", value, "IS_EXPIRED");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDLessThan(String value) {
            addCriterion("IS_EXPIRED <", value, "IS_EXPIRED");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDLessThanOrEqualTo(String value) {
            addCriterion("IS_EXPIRED <=", value, "IS_EXPIRED");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDLike(String value) {
            addCriterion("IS_EXPIRED like", value, "IS_EXPIRED");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDNotLike(String value) {
            addCriterion("IS_EXPIRED not like", value, "IS_EXPIRED");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDIn(List<String> values) {
            addCriterion("IS_EXPIRED in", values, "IS_EXPIRED");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDNotIn(List<String> values) {
            addCriterion("IS_EXPIRED not in", values, "IS_EXPIRED");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDBetween(String value1, String value2) {
            addCriterion("IS_EXPIRED between", value1, value2, "IS_EXPIRED");
            return (Criteria) this;
        }

        public Criteria andIS_EXPIREDNotBetween(String value1, String value2) {
            addCriterion("IS_EXPIRED not between", value1, value2, "IS_EXPIRED");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALIsNull() {
            addCriterion("IS_TRIAL is null");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALIsNotNull() {
            addCriterion("IS_TRIAL is not null");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALEqualTo(String value) {
            addCriterion("IS_TRIAL =", value, "IS_TRIAL");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALNotEqualTo(String value) {
            addCriterion("IS_TRIAL <>", value, "IS_TRIAL");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALGreaterThan(String value) {
            addCriterion("IS_TRIAL >", value, "IS_TRIAL");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALGreaterThanOrEqualTo(String value) {
            addCriterion("IS_TRIAL >=", value, "IS_TRIAL");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALLessThan(String value) {
            addCriterion("IS_TRIAL <", value, "IS_TRIAL");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALLessThanOrEqualTo(String value) {
            addCriterion("IS_TRIAL <=", value, "IS_TRIAL");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALLike(String value) {
            addCriterion("IS_TRIAL like", value, "IS_TRIAL");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALNotLike(String value) {
            addCriterion("IS_TRIAL not like", value, "IS_TRIAL");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALIn(List<String> values) {
            addCriterion("IS_TRIAL in", values, "IS_TRIAL");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALNotIn(List<String> values) {
            addCriterion("IS_TRIAL not in", values, "IS_TRIAL");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALBetween(String value1, String value2) {
            addCriterion("IS_TRIAL between", value1, value2, "IS_TRIAL");
            return (Criteria) this;
        }

        public Criteria andIS_TRIALNotBetween(String value1, String value2) {
            addCriterion("IS_TRIAL not between", value1, value2, "IS_TRIAL");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYIsNull() {
            addCriterion("FREQUENCY is null");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYIsNotNull() {
            addCriterion("FREQUENCY is not null");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYEqualTo(String value) {
            addCriterion("FREQUENCY =", value, "FREQUENCY");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYNotEqualTo(String value) {
            addCriterion("FREQUENCY <>", value, "FREQUENCY");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYGreaterThan(String value) {
            addCriterion("FREQUENCY >", value, "FREQUENCY");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYGreaterThanOrEqualTo(String value) {
            addCriterion("FREQUENCY >=", value, "FREQUENCY");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYLessThan(String value) {
            addCriterion("FREQUENCY <", value, "FREQUENCY");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYLessThanOrEqualTo(String value) {
            addCriterion("FREQUENCY <=", value, "FREQUENCY");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYLike(String value) {
            addCriterion("FREQUENCY like", value, "FREQUENCY");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYNotLike(String value) {
            addCriterion("FREQUENCY not like", value, "FREQUENCY");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYIn(List<String> values) {
            addCriterion("FREQUENCY in", values, "FREQUENCY");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYNotIn(List<String> values) {
            addCriterion("FREQUENCY not in", values, "FREQUENCY");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYBetween(String value1, String value2) {
            addCriterion("FREQUENCY between", value1, value2, "FREQUENCY");
            return (Criteria) this;
        }

        public Criteria andFREQUENCYNotBetween(String value1, String value2) {
            addCriterion("FREQUENCY not between", value1, value2, "FREQUENCY");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHIsNull() {
            addCriterion("IS_AUTO_PUBLISH is null");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHIsNotNull() {
            addCriterion("IS_AUTO_PUBLISH is not null");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHEqualTo(String value) {
            addCriterion("IS_AUTO_PUBLISH =", value, "IS_AUTO_PUBLISH");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHNotEqualTo(String value) {
            addCriterion("IS_AUTO_PUBLISH <>", value, "IS_AUTO_PUBLISH");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHGreaterThan(String value) {
            addCriterion("IS_AUTO_PUBLISH >", value, "IS_AUTO_PUBLISH");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHGreaterThanOrEqualTo(String value) {
            addCriterion("IS_AUTO_PUBLISH >=", value, "IS_AUTO_PUBLISH");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHLessThan(String value) {
            addCriterion("IS_AUTO_PUBLISH <", value, "IS_AUTO_PUBLISH");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHLessThanOrEqualTo(String value) {
            addCriterion("IS_AUTO_PUBLISH <=", value, "IS_AUTO_PUBLISH");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHLike(String value) {
            addCriterion("IS_AUTO_PUBLISH like", value, "IS_AUTO_PUBLISH");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHNotLike(String value) {
            addCriterion("IS_AUTO_PUBLISH not like", value, "IS_AUTO_PUBLISH");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHIn(List<String> values) {
            addCriterion("IS_AUTO_PUBLISH in", values, "IS_AUTO_PUBLISH");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHNotIn(List<String> values) {
            addCriterion("IS_AUTO_PUBLISH not in", values, "IS_AUTO_PUBLISH");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHBetween(String value1, String value2) {
            addCriterion("IS_AUTO_PUBLISH between", value1, value2, "IS_AUTO_PUBLISH");
            return (Criteria) this;
        }

        public Criteria andIS_AUTO_PUBLISHNotBetween(String value1, String value2) {
            addCriterion("IS_AUTO_PUBLISH not between", value1, value2, "IS_AUTO_PUBLISH");
            return (Criteria) this;
        }

        public Criteria andRPT_URLIsNull() {
            addCriterion("RPT_URL is null");
            return (Criteria) this;
        }

        public Criteria andRPT_URLIsNotNull() {
            addCriterion("RPT_URL is not null");
            return (Criteria) this;
        }

        public Criteria andRPT_URLEqualTo(String value) {
            addCriterion("RPT_URL =", value, "RPT_URL");
            return (Criteria) this;
        }

        public Criteria andRPT_URLNotEqualTo(String value) {
            addCriterion("RPT_URL <>", value, "RPT_URL");
            return (Criteria) this;
        }

        public Criteria andRPT_URLGreaterThan(String value) {
            addCriterion("RPT_URL >", value, "RPT_URL");
            return (Criteria) this;
        }

        public Criteria andRPT_URLGreaterThanOrEqualTo(String value) {
            addCriterion("RPT_URL >=", value, "RPT_URL");
            return (Criteria) this;
        }

        public Criteria andRPT_URLLessThan(String value) {
            addCriterion("RPT_URL <", value, "RPT_URL");
            return (Criteria) this;
        }

        public Criteria andRPT_URLLessThanOrEqualTo(String value) {
            addCriterion("RPT_URL <=", value, "RPT_URL");
            return (Criteria) this;
        }

        public Criteria andRPT_URLLike(String value) {
            addCriterion("RPT_URL like", value, "RPT_URL");
            return (Criteria) this;
        }

        public Criteria andRPT_URLNotLike(String value) {
            addCriterion("RPT_URL not like", value, "RPT_URL");
            return (Criteria) this;
        }

        public Criteria andRPT_URLIn(List<String> values) {
            addCriterion("RPT_URL in", values, "RPT_URL");
            return (Criteria) this;
        }

        public Criteria andRPT_URLNotIn(List<String> values) {
            addCriterion("RPT_URL not in", values, "RPT_URL");
            return (Criteria) this;
        }

        public Criteria andRPT_URLBetween(String value1, String value2) {
            addCriterion("RPT_URL between", value1, value2, "RPT_URL");
            return (Criteria) this;
        }

        public Criteria andRPT_URLNotBetween(String value1, String value2) {
            addCriterion("RPT_URL not between", value1, value2, "RPT_URL");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wd_report
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 21 20:19:24 EDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wd_report
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}