package com.rstech.wordwatch.dao;

public class WordReportEntryAux {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report_entry_aux.ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report_entry_aux.WD_REPORT_ENTRY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private Long WD_REPORT_ENTRY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report_entry_aux.AUX_KEY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String AUX_KEY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report_entry_aux.AUX_VALUE
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    private String AUX_VALUE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report_entry_aux.ID
     *
     * @return the value of wd_report_entry_aux.ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report_entry_aux.ID
     *
     * @param ID the value for wd_report_entry_aux.ID
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report_entry_aux.WD_REPORT_ENTRY
     *
     * @return the value of wd_report_entry_aux.WD_REPORT_ENTRY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public Long getWD_REPORT_ENTRY() {
        return WD_REPORT_ENTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report_entry_aux.WD_REPORT_ENTRY
     *
     * @param WD_REPORT_ENTRY the value for wd_report_entry_aux.WD_REPORT_ENTRY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setWD_REPORT_ENTRY(Long WD_REPORT_ENTRY) {
        this.WD_REPORT_ENTRY = WD_REPORT_ENTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report_entry_aux.AUX_KEY
     *
     * @return the value of wd_report_entry_aux.AUX_KEY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getAUX_KEY() {
        return AUX_KEY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report_entry_aux.AUX_KEY
     *
     * @param AUX_KEY the value for wd_report_entry_aux.AUX_KEY
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setAUX_KEY(String AUX_KEY) {
        this.AUX_KEY = AUX_KEY == null ? null : AUX_KEY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report_entry_aux.AUX_VALUE
     *
     * @return the value of wd_report_entry_aux.AUX_VALUE
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public String getAUX_VALUE() {
        return AUX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report_entry_aux.AUX_VALUE
     *
     * @param AUX_VALUE the value for wd_report_entry_aux.AUX_VALUE
     *
     * @mbggenerated Wed Oct 21 20:19:24 EDT 2015
     */
    public void setAUX_VALUE(String AUX_VALUE) {
        this.AUX_VALUE = AUX_VALUE == null ? null : AUX_VALUE.trim();
    }
}