package com.rstech.wordwatch.dao;

import java.util.Date;

public class WordReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.ID
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.RS_CLIENT
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private Long RS_CLIENT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.REPORT_TYPE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String REPORT_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.TITLE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String TITLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.STATUS
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.REPORTS_RUN
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private Short REPORTS_RUN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.FIRST_RUN_DATE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private Date FIRST_RUN_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.LAST_RUN_DATE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private Date LAST_RUN_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.EXPIRATION_DATE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private Date EXPIRATION_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.DESCRIPTION
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String DESCRIPTION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.IS_DELETED
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String IS_DELETED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.VERSION
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private Integer VERSION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.IS_EXPIRED
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String IS_EXPIRED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.IS_TRIAL
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String IS_TRIAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.FREQUENCY
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String FREQUENCY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.IS_AUTO_PUBLISH
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String IS_AUTO_PUBLISH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_report.RPT_URL
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    private String RPT_URL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.ID
     *
     * @return the value of wd_report.ID
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.ID
     *
     * @param ID the value for wd_report.ID
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.RS_CLIENT
     *
     * @return the value of wd_report.RS_CLIENT
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Long getRS_CLIENT() {
        return RS_CLIENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.RS_CLIENT
     *
     * @param RS_CLIENT the value for wd_report.RS_CLIENT
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setRS_CLIENT(Long RS_CLIENT) {
        this.RS_CLIENT = RS_CLIENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.REPORT_TYPE
     *
     * @return the value of wd_report.REPORT_TYPE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getREPORT_TYPE() {
        return REPORT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.REPORT_TYPE
     *
     * @param REPORT_TYPE the value for wd_report.REPORT_TYPE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setREPORT_TYPE(String REPORT_TYPE) {
        this.REPORT_TYPE = REPORT_TYPE == null ? null : REPORT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.TITLE
     *
     * @return the value of wd_report.TITLE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getTITLE() {
        return TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.TITLE
     *
     * @param TITLE the value for wd_report.TITLE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setTITLE(String TITLE) {
        this.TITLE = TITLE == null ? null : TITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.STATUS
     *
     * @return the value of wd_report.STATUS
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.STATUS
     *
     * @param STATUS the value for wd_report.STATUS
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.REPORTS_RUN
     *
     * @return the value of wd_report.REPORTS_RUN
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Short getREPORTS_RUN() {
        return REPORTS_RUN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.REPORTS_RUN
     *
     * @param REPORTS_RUN the value for wd_report.REPORTS_RUN
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setREPORTS_RUN(Short REPORTS_RUN) {
        this.REPORTS_RUN = REPORTS_RUN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.FIRST_RUN_DATE
     *
     * @return the value of wd_report.FIRST_RUN_DATE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Date getFIRST_RUN_DATE() {
        return FIRST_RUN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.FIRST_RUN_DATE
     *
     * @param FIRST_RUN_DATE the value for wd_report.FIRST_RUN_DATE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setFIRST_RUN_DATE(Date FIRST_RUN_DATE) {
        this.FIRST_RUN_DATE = FIRST_RUN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.LAST_RUN_DATE
     *
     * @return the value of wd_report.LAST_RUN_DATE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Date getLAST_RUN_DATE() {
        return LAST_RUN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.LAST_RUN_DATE
     *
     * @param LAST_RUN_DATE the value for wd_report.LAST_RUN_DATE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setLAST_RUN_DATE(Date LAST_RUN_DATE) {
        this.LAST_RUN_DATE = LAST_RUN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.EXPIRATION_DATE
     *
     * @return the value of wd_report.EXPIRATION_DATE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Date getEXPIRATION_DATE() {
        return EXPIRATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.EXPIRATION_DATE
     *
     * @param EXPIRATION_DATE the value for wd_report.EXPIRATION_DATE
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setEXPIRATION_DATE(Date EXPIRATION_DATE) {
        this.EXPIRATION_DATE = EXPIRATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.DESCRIPTION
     *
     * @return the value of wd_report.DESCRIPTION
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.DESCRIPTION
     *
     * @param DESCRIPTION the value for wd_report.DESCRIPTION
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.IS_DELETED
     *
     * @return the value of wd_report.IS_DELETED
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getIS_DELETED() {
        return IS_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.IS_DELETED
     *
     * @param IS_DELETED the value for wd_report.IS_DELETED
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setIS_DELETED(String IS_DELETED) {
        this.IS_DELETED = IS_DELETED == null ? null : IS_DELETED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.VERSION
     *
     * @return the value of wd_report.VERSION
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public Integer getVERSION() {
        return VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.VERSION
     *
     * @param VERSION the value for wd_report.VERSION
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setVERSION(Integer VERSION) {
        this.VERSION = VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.IS_EXPIRED
     *
     * @return the value of wd_report.IS_EXPIRED
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getIS_EXPIRED() {
        return IS_EXPIRED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.IS_EXPIRED
     *
     * @param IS_EXPIRED the value for wd_report.IS_EXPIRED
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setIS_EXPIRED(String IS_EXPIRED) {
        this.IS_EXPIRED = IS_EXPIRED == null ? null : IS_EXPIRED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.IS_TRIAL
     *
     * @return the value of wd_report.IS_TRIAL
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getIS_TRIAL() {
        return IS_TRIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.IS_TRIAL
     *
     * @param IS_TRIAL the value for wd_report.IS_TRIAL
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setIS_TRIAL(String IS_TRIAL) {
        this.IS_TRIAL = IS_TRIAL == null ? null : IS_TRIAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.FREQUENCY
     *
     * @return the value of wd_report.FREQUENCY
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getFREQUENCY() {
        return FREQUENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.FREQUENCY
     *
     * @param FREQUENCY the value for wd_report.FREQUENCY
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setFREQUENCY(String FREQUENCY) {
        this.FREQUENCY = FREQUENCY == null ? null : FREQUENCY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.IS_AUTO_PUBLISH
     *
     * @return the value of wd_report.IS_AUTO_PUBLISH
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getIS_AUTO_PUBLISH() {
        return IS_AUTO_PUBLISH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.IS_AUTO_PUBLISH
     *
     * @param IS_AUTO_PUBLISH the value for wd_report.IS_AUTO_PUBLISH
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setIS_AUTO_PUBLISH(String IS_AUTO_PUBLISH) {
        this.IS_AUTO_PUBLISH = IS_AUTO_PUBLISH == null ? null : IS_AUTO_PUBLISH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_report.RPT_URL
     *
     * @return the value of wd_report.RPT_URL
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public String getRPT_URL() {
        return RPT_URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_report.RPT_URL
     *
     * @param RPT_URL the value for wd_report.RPT_URL
     *
     * @mbggenerated Mon Jul 04 20:46:26 EDT 2016
     */
    public void setRPT_URL(String RPT_URL) {
        this.RPT_URL = RPT_URL == null ? null : RPT_URL.trim();
    }
}