package com.rstech.wordwatch.dao;

public class WordFieldList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_field_list.ID
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_field_list.REC_TYPE
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    private String REC_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_field_list.REC_SUB_TYPE
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    private String REC_SUB_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_field_list.FIELD_NAME
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    private String FIELD_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_field_list.REQ_ORDER
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    private Short REQ_ORDER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_field_list.DISPLAY_ORDER
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    private Short DISPLAY_ORDER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_field_list.IS_DELETED
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    private String IS_DELETED;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_field_list.VERSION
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    private Integer VERSION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_field_list.ID
     *
     * @return the value of word_field_list.ID
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_field_list.ID
     *
     * @param ID the value for word_field_list.ID
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_field_list.REC_TYPE
     *
     * @return the value of word_field_list.REC_TYPE
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public String getREC_TYPE() {
        return REC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_field_list.REC_TYPE
     *
     * @param REC_TYPE the value for word_field_list.REC_TYPE
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public void setREC_TYPE(String REC_TYPE) {
        this.REC_TYPE = REC_TYPE == null ? null : REC_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_field_list.REC_SUB_TYPE
     *
     * @return the value of word_field_list.REC_SUB_TYPE
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public String getREC_SUB_TYPE() {
        return REC_SUB_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_field_list.REC_SUB_TYPE
     *
     * @param REC_SUB_TYPE the value for word_field_list.REC_SUB_TYPE
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public void setREC_SUB_TYPE(String REC_SUB_TYPE) {
        this.REC_SUB_TYPE = REC_SUB_TYPE == null ? null : REC_SUB_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_field_list.FIELD_NAME
     *
     * @return the value of word_field_list.FIELD_NAME
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public String getFIELD_NAME() {
        return FIELD_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_field_list.FIELD_NAME
     *
     * @param FIELD_NAME the value for word_field_list.FIELD_NAME
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public void setFIELD_NAME(String FIELD_NAME) {
        this.FIELD_NAME = FIELD_NAME == null ? null : FIELD_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_field_list.REQ_ORDER
     *
     * @return the value of word_field_list.REQ_ORDER
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public Short getREQ_ORDER() {
        return REQ_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_field_list.REQ_ORDER
     *
     * @param REQ_ORDER the value for word_field_list.REQ_ORDER
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public void setREQ_ORDER(Short REQ_ORDER) {
        this.REQ_ORDER = REQ_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_field_list.DISPLAY_ORDER
     *
     * @return the value of word_field_list.DISPLAY_ORDER
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public Short getDISPLAY_ORDER() {
        return DISPLAY_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_field_list.DISPLAY_ORDER
     *
     * @param DISPLAY_ORDER the value for word_field_list.DISPLAY_ORDER
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public void setDISPLAY_ORDER(Short DISPLAY_ORDER) {
        this.DISPLAY_ORDER = DISPLAY_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_field_list.IS_DELETED
     *
     * @return the value of word_field_list.IS_DELETED
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public String getIS_DELETED() {
        return IS_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_field_list.IS_DELETED
     *
     * @param IS_DELETED the value for word_field_list.IS_DELETED
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public void setIS_DELETED(String IS_DELETED) {
        this.IS_DELETED = IS_DELETED == null ? null : IS_DELETED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_field_list.VERSION
     *
     * @return the value of word_field_list.VERSION
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public Integer getVERSION() {
        return VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_field_list.VERSION
     *
     * @param VERSION the value for word_field_list.VERSION
     *
     * @mbggenerated Mon Nov 05 19:59:23 EST 2012
     */
    public void setVERSION(Integer VERSION) {
        this.VERSION = VERSION;
    }
}